munich-quantum-toolkit/core

- include/operations/Operation.hpp
- src/operations/Operation.cpp
- src/operations/StandardOperation.cpp
- src/parsers/RealParser.cpp
- Preparation for adding Teleportation to QMAP
- Updated submodule for pybind
> Added Teleportation Operation

- include/QuantumComputation.hpp
- include/operations/CompoundOperation.hpp
- include/parsers/qasm_parser/Token.hpp
- src/algorithms/Grover.cpp
- src/parsers/QASMParser.cpp
- src/parsers/qasm_parser/Parser.cpp
- src/parsers/qasm_parser/Scanner.cpp
- test/unittests/test_io.cpp
✨ `mcphase` gate dumped by Qiskit is now natively supported
🐛/✨ declarations of gates that are natively supported are skipped
🚸 `QuantumComputation` and `CompoundOperation` now have an `at` member function for directly accessing the underlying vector of operations
✅ add tests for new features
⬆️ update submodules
🐛 address compilation error when changing the `dd::Qubit` type (resolves iic-jku/qcec#7)
> ✨ Improve QASM Parser

- CMakeLists.txt
- setup.py
- src/algorithms/Grover.cpp
Recent updates in the DDPackage repository bring improvements for numerical stability (iic-jku/dd_package#21) and (among others) visualization (iic-jku/dd_package#20).
This PR updates the QFR to this new version.
(It also brings a small improvement in the reference counting in Grover's algorithm)
> Update to new DD Package Version

- jkq/qfr/qiskit/QasmQobjExperiment.hpp
- jkq/qfr/qiskit/QuantumCircuit.hpp
This PR fixes some compiler warnings in the bindings code and updates all the submodules to their latest version.
> Fix compiler warnings

- include/CircuitOptimizer.hpp
- include/operations/CompoundOperation.hpp
- src/CircuitOptimizer.cpp
- test/unittests/test_qfr_functionality.cpp
This PR adds a new optimization pass that allows to flatten circuits containing compound operations.
> ✨ Flattening Circuits

- include/operations/ClassicControlledOperation.hpp
- include/operations/CompoundOperation.hpp
- include/operations/NonUnitaryOperation.hpp
- include/operations/Operation.hpp
- include/operations/StandardOperation.hpp
- src/operations/NonUnitaryOperation.cpp
- src/operations/Operation.cpp
- test/unittests/test_qfr_functionality.cpp
This PR adds equality checks for operations.
> ✨Equality checks for Operations

- include/operations/OpType.hpp
This PR adds some missing operation synonyms to ease the import from Qiskit.
> 🐛 add some missing synonymous operation names

- include/QuantumComputation.hpp
- src/QuantumComputation.cpp
- test/unittests/test_qfr_functionality.cpp
Added methods that check whether executing a given operation makes sense with respect to the indices of the initial layout.
> Qubit sanity check

- .github/dependabot.yml
Set timezone to Europe/Vienna.
> Update timezones for dependabot

- src/zx/FunctionalityConstruction.cpp
- test/CMakeLists.txt
- test/unittests/test_zx_functionality.cpp
Added global phases to certain gates (like RZ) during parsing.
> Global phase

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/deploy.yml
This PR updates the CI configuration with the latest best practices within the MQT.
> 🔧  CI Config Update

- src/CMakeLists.txt
This small PR makes sure that CMake are only added if they do not exist already. This avoids problems when multiple versions of the DDPackage are part of the same repository
> 🚸 only add CMake targets if they do not exist

- include/dd/Definitions.hpp
- include/dd/Export.hpp
- include/dd/UniqueTable.hpp
This PR addresses the relevant CodeQL warnings raised in the main PR.
> 🚨 CodeQL Fixes

- .git_archival.txt
- .gitattributes
Following https://scikit-hep.org/developer/packaging#versioning-mediumhigh-priority, this PR adds the necessary steps to allow git archives (including the ones generated from GitHub) to also support versioning.
> 📦 Support Versioning in Git Archives

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
> ✨ Add release drafter setup

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/pull_request_template.md
> ✨ add Issue and PR templates

- .github/contributing.rst
- .github/support.rst
> ✨ add community health files

- .github/workflows/ci.yml
- cmake/StandardProjectSettings.cmake
Makes IPO opt-in. This might change coverage reporting.
Fixes #342
> 🔧 Disable IPO per default

- .github/SECURITY.md
Adds a security policy to the project.
> 🔒 add security policy

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/cpp-linter.yml
- .github/workflows/emulated-wheels.yml
- .github/workflows/python-ci.yml
- .github/workflows/release-drafter.yml
- .github/workflows/wheels.yml
- .pre-commit-config.yaml
- docs/conf.py
- noxfile.py
- pyproject.toml
- src/mqt/core/_core/__init__.pyi
- src/mqt/core/_version.pyi
This PR set up all the infrastructure for developing a modern `mqt.core` Python package.
Instead of relying on `pybind11` and `setuptools` it uses [scikit-build-core](https://github.com/scikit-build/scikit-build-core) and [nanobind](https://github.com/wjakob/nanobind) to create a C++ extension module and package everything as a complete Python package.
This is a substantial improvement over all previous efforts that relied on setuptools. For example, the new setup allows for fast, editable installs where the Python package is automatically rebuilt on C++ source code changes.
Furthermore, `nanobind` is directly included as a build time dependency and need not be included as a git submodule.
Finally, all the nasty configuration from the `setup.py` file could be removed. In fact, there no …
> 🎉🐍 Initial `mqt.core` Python Package Configuration

- include/dd/ComplexNumbers.hpp
- include/dd/Export.hpp
- include/dd/Package.hpp
- src/QuantumComputation.cpp
- src/dd/Simulation.cpp
- test/dd/test_complex.cpp
- test/dd/test_package.cpp
- test/unittests/test_io.cpp
- test/unittests/test_qfr_functionality.cpp
This PR tries to improve the overall code quality by eliminating some compiler warnings, fixing the reported GitHub CodeQL warnings, and improving some of the testing code.
I expect more of these PRs to come in the next couple of weeks to gradually improve the overall code quality.
> 🚨♻️ Fix some warnings and improve code quality

- .pre-commit-config.yaml
For reference: https://black.readthedocs.io/en/latest/integrations/source_version_control.html
> ⚡ use 2x faster black mirror

- .github/workflows/reusable-change-detection.yml
- CMakeLists.txt
Just a small CMake configuration update that simplifies some configuration.
> 🔧 Add policy max to CMake minimum required version

- src/algorithms/QPE.cpp
This fixes a bug in the construction logic for the QPE algorithm that led to the algorithm not constructing inexact instances reliably.
> 🐛 Fix inexact QPE construction

- .github/workflows/reusable-code-ql-cpp.yml
- .github/workflows/reusable-code-ql-python.yml
- .github/workflows/reusable-python-packaging.yml
This PR fixes a few oversights in the reusable workflows that might have caused some unintended side effects.
> 🩹 Reusable workflow corrections

- include/dd/Complex.hpp
- include/dd/ComplexNumbers.hpp
- include/dd/ComplexValue.hpp
- include/dd/Export.hpp
- include/dd/Node.hpp
- include/dd/NoiseFunctionality.hpp
- include/dd/Package.hpp
- include/dd/RealNumber.hpp
- src/dd/Complex.cpp
- src/dd/ComplexNumbers.cpp
- src/dd/ComplexValue.cpp
- src/dd/RealNumber.cpp
- src/operations/Operation.cpp
- test/algorithms/test_wstate.cpp
- test/dd/test_dd_noise_functionality.cpp
This PR is another one in the series of reducing #444 and extracting useful changes.
In this case, some rather miscellaneous improvements throughout the package.
> 🎨 Miscellaneous code style improvements in DD package

- .pre-commit-config.yaml
- pyproject.toml
This PR adopts ruff's new formatter as a drop-in replacement for black. See https://astral.sh/blog/the-ruff-formatter for a nice introduction. It's faster, allows us to drop a dependency and reduces configuration.
> ✨ adopt ruff formatter

- docs/conf.py
- pyproject.toml
- src/mqt/core/_compat/typing.py
- src/mqt/core/plugins/qiskit.py
A couple of small updates and new rules for ruff
> 🚨 small ruff updates

- .pre-commit-config.yaml
- pyproject.toml
This PR adopts Scientific Python's repo-review that is based on the [Scientific Python Development Guide](https://learn.scientific-python.org/development/) and checks the repository for common best practices.
> ✨ add Scientific Python's repo-review

- CMakeLists.txt
This small PR updates the maximum supported CMake version to 3.28
> 🚸 update maximum supported CMake version

- docs/quickstart.ipynb
This PR adjusts the documentation to the newly available OpenQASM 3 support.
> 📝 update documentation with OpenQASM 3.0 support

- .readthedocs.yaml
- README.md
- docs/conf.py
This PR adds basic configuration for supporting RtD offline formats.
While the formatting is not perfect yet, this is a solid start for providing some downloadable offline documentation.
> 📝 add configuration for offline doc formats

- pyproject.toml
This PR ignores a new DeprecationWarning issued by pandas. This should let the CI pipeline pass again.
> 🚨 ignore new pandas deprecation warning

- docs/_static/custom.css
This PR improves the dark-mode documentation by improving how strings are highlighted.
> 📝🎨 better dark mode docs

- include/mqt-core/dd/Package.hpp
This PR slightly improves the performance of the conjugate transpose in the DD package.
It does so by reducing the size of the keys stored in the compute table and enabling more potential hits because the top edge weight no longer factors into the lookup.
This also brings conjugate transposition more in line with the other operations that use compute tables.
> ⚡ optimize conjugate transpose in DD package

- .readthedocs.yaml
This PR revamps the RtD configuration to make use of `uv` for faster builds.
> :zap: faster RtD

- include/mqt-core/operations/AodOperation.hpp
- src/operations/AodOperation.cpp
Fixes a couple of small shadowing compiler warnings that were introduced in a recent PR.
> 🚨 fix shadowing compiler warnings

- pyproject.toml
This PR fixes a small mistake in the ruff configuration for the `banned-api` check.
> 🚨🩹 fix the ruff `banned-api` configuration

- docs/conf.py
This small PR fixes the latex docs build that was broken due to some update regarding the `fontawesome` package.
> 🩹📝 fix docs build

- .pre-commit-config.yaml
- noxfile.py
- pyproject.toml
This PR updates the project to the latest scikit-build-core version that was just released and adapts the configuration correspondingly.
> ⬆️ update to scikit-build-core 0.10

- noxfile.py
This PR brings some small improvements to the project's `nox` sessions.
> 🚸 improve nox sessions

- include/mqt-core/dd/DDpackageConfig.hpp
- include/mqt-core/dd/Package.hpp
- src/dd/FunctionalityConstruction.cpp
This PR adds a dedicated DD package configuration for the unitary simulator in DDSim that is fine-tuned for the respective requirements.
Related to https://github.com/cda-tum/mqt-ddsim/issues/182
> ⚡ dedicated unitary simulator DD package config

- .github/renovate.json5
- .github/workflows/release-drafter.yml
- .pre-commit-config.yaml
Small tweaks to the renovate configuration to slighlty reduce the frequency of updates and enabling automerge for patch version updates.
> 🔧 update renovate configuration

- .github/release-drafter.yml
- .github/renovate.json5
This PR slightly updates the release drafter and the corresponding renovate configuration to yield more readable release notes.
> 🔧 update release drafter template and renovate config

- .readthedocs.yaml
This PR adjusts the RtD config to unshallow the git clone which should allow to get proper versioning information for latest docs builds.
> 🔧📝 unshallow git clone for RtD

- eval/eval_dd_package.cpp
- include/mqt-core/dd/Operations.hpp
- include/mqt-core/dd/Package.hpp
- src/dd/Simulation.cpp
This is a direct follow-up to #674 and adds one more convenience routine that avoids users having to perform reference counting on their own.
> 🎨 further DD usability improvements

- pyproject.toml
This small PR updates the Python coverage collection configuration to exclude additional constructs that may not be possible to cover by tests.
> 🔧 update Python coverage configuration

- .github/workflows/cd.yml
- .github/workflows/ci.yml
This small PR updates the MQT workflows to version 1.7, which includes some fixes for CD jobs that were overlooked in v1.6
> 👷⬆️ update MQT workflows to v1.7

- .github/contributing.md
- docs/DevelopmentGuide.md
- docs/installation.md
This pull request updates the development guide to make it more modern and easier to follow. 
This effort improves the documentation and ensures it aligns with current practices.
Hopefully, this can serve as the blueprint for many other MQT repositories.
> ✨📝 Rework and modernize the development guide

- include/mqt-core/Definitions.hpp
- include/mqt-core/dd/FunctionalityConstruction.hpp
- include/mqt-core/dd/Operations.hpp
- include/mqt-core/dd/Simulation.hpp
- include/mqt-core/ir/operations/Control.hpp
- src/python/ir/register_quantum_computation.cpp
This PR slighlty improves documentation and adds a more convenient `__repr__` for QuantumComputations.
> 📝 Slightly improve code documentation and `QuantumComputation.__repr__`

- docs/DevelopmentGuide.md
- docs/conf.py
This pull request removes an outdated paragraph from the documentation and updates the copyright year to the current year. These changes ensure that the documentation is accurate and up to date.
> 📝 Update documentation to reflect recent changes

- eval/eval_dd_package.cpp
- src/mqt/core/dd_evaluation.py
This pull request addresses a division by zero error, ensuring the application handles such scenarios gracefully. Additionally, it includes a minor adjustment to evaluation settings for the DD Package evaluation.
> ⚗️ Fix potential division by zero error and tweak DD evaluation settings

- include/mqt-core/dd/CachedEdge.hpp
- include/mqt-core/dd/Edge.hpp
- src/dd/CachedEdge.cpp
- src/dd/Edge.cpp
Just a small byproduct of a debugging session that eventually boiled down to LLVM@20 and AppleClang@17 not being binary compatible.
Thee PR merely contains syntactic sugar and code style improvements.
> 🎨 slightly touch up template instantiations and use more trailing return types

- CMakeLists.txt
- cmake/ExternalDependencies.cmake
This PR slighlty updates and modernizes some of the CMake configuration. It indicates support for CMake 4, configures the C compiler in addition to the C++ compiler, and requires the proper version of pybind11.
> 🔧 Minor updates for CMake configuration

- pyproject.toml
- uv.lock
This PR updates the lower bounds for some of our development dependencies to their latest version.
> ⬆️ update lower bounds of dev dependencies

- .github/contributing.md
- .github/release-drafter.yml
- CHANGELOG.md
- UPGRADING.md
- docs/CHANGELOG.md
- docs/UPGRADING.md
- docs/index.md
This PR adds a dedicated changelog and upgrade guide to the project as a centralized place to keep track of significant updates to this library.
Both of these files are curated selections of the PRs that go into a release.
Notably, these are written for humans and not for machines.
As such, they are not automatically scraped together like the drafts created by the release drafter action. These drafts may still serve as blueprints for corresponding changelog entries.
> ✨📝 Add changelog and upgrade guide infrastructure

- include/mqt-core/dd/Operations.hpp
- include/mqt-core/ir/QuantumComputation.hpp
- src/dd/Operations.cpp
- src/dd/Simulation.cpp
This pull request adds an handful of helper functions for the `simulate` and `sample` functions in an unnamed namespace.
> 🎨 Add Helper Functions For `simulate` And `sample`

- CHANGELOG.md
- cmake/ExternalDependencies.cmake
This PR updates the `nlohmann_json` dependency to its latest version, which brings a large range of updates for the underlying library.
> ⬆️ update nlohmann_json to `v3.12.0`

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/pull_request_template.md
- .license-tools-config.json
- pyproject.toml
This pull request updates the pull request and issue templates to improve their clarity and usability. Additionally, it updates the configuration for license tools.
> 📝 Update templates and license tools configuration

- CHANGELOG.md
- docs/conf.py
This PR slightly refines the changelog by pulling out links to the bottom of the document, which makes the changelog much easier to read in an environment without markdown rendering such as git diffs.
Along the way, this PR also fixes the PDF docs build by adding the missing unicode mappings.
> 📝 Refine changelog

- include/mqt-core/dd/ComputeTable.hpp
- include/mqt-core/dd/UnaryComputeTable.hpp
- include/mqt-core/dd/UniqueTable.hpp
Since work on #883 has stalled, this PR pulls out a couple of small but nice code quality changes for the unique and compute tables in the DD package from it before that PR is (temporarily) closed.
> 🎨 Tiny improvements for DD compute table and unique table code

- noxfile.py
- pyproject.toml
- sitecustomize.py
- test/python/test_load.py
- uv.lock
This PR speeds up the test suite. It is a copy of https://github.com/munich-quantum-toolkit/bench/pull/602.
> ⚡ Speed up test suite

- .github/workflows/templating.yml
This PR updates the templating workflow to use v1.0.0 of the action.
> 👷 Update templating workflow to use v1.0.0

- mlir/lib/Dialect/MQTOpt/Transforms/MergeRotationGatesPattern.cpp
Extracting this from #881 because it is independent from the plugin.
During #1046, one of the transformation passes was missed and was still using `match` and `rewrite` instead of the combined `matchAndRewrite`.
This PR fixes that oversight.
> ♻️ one more `match` and `rewrite` replacement

- .github/workflows/ci.yml
This PR fixes the condition for triggering the Python coverage job.
> 🐛👷 Fix condition for Python coverage

- .github/workflows/ci.yml
- .github/workflows/upstream.yml
This PR implements some changes made in the other C++ repositories:
- Test one Debug build for every OS
- Run Qiskit upstream tests on `macos-14` and `windows-2022`
> 👷 Always test selected Debug builds

- CHANGELOG.md
- UPGRADING.md
This PR prepares the release of v3.2.0.
> 🔖 Prepare release of v3.2.0

- include/mqt-core/dd/Package.hpp
This PR fixes a bug in the DD package that I introduced in https://github.com/munich-quantum-toolkit/core/pull/897/commits/eb1cbfc4177b52a9166f5ea9ac695088252e3267.
> 🐛 Fix bug in DD package

- docs/dd_package.md
This fixes an oversight in the DD docs where the syntax was not updated and the script was actually failing without us noticing.
@denialhaag at some point we should look into actually making the docs pipeline fail whenever the docs execution fails. There should be a setting for that.
> ✏️ fix DD documentation page

- .readthedocs.yaml
- CMakeLists.txt
- cmake/CleanMLIRDocs.cmake
- docs/mlir/MQTOpt.md
- docs/mlir/MQTRef.md
- docs/mlir/index.md
- pyproject.toml
- uv.lock
This PR optimizes the MLIR documentation setup:
- adds a dedicated and newly-created `mlir-pygments` package to provide syntax highlighting for MLIR code blocks
- fixes a link in the MLIR docs
- moves the cleanup logic from the RtD setup to the CMake setup so that it can be replicated locally
- optimizes the page display for the MLIR docs pages.
> 📝 Optimize MLIR documentation setup
