munich-quantum-toolkit/core

.gitmodules, CMakeLists.txt, LICENSE.md, include/operations/CompoundOperation.hpp, include/operations/Operation.hpp, include/operations/StandardOperation.hpp, setup.py, src/operations/StandardOperation.cpp
This PR adds the essential functionality to the JKQ QFR library to support hybrid Schrödinger-Feynman simulation.
The main change is that operations now support a `startQubit` for generating DDs not starting from 0, which is needed for splitting the circuit horizontally.
✨ Operations now contain an additional startQubit (default 0) indicating from which Qubit the DD that should be built starts from
🐛 fix incorrect type in CompoundOperation.hpp constructor
⬆️ update all submodules
=> Hybrid Schrödinger-Feynman Simulation Preparation

include/CircuitOptimizer.hpp, src/CircuitOptimizer.cpp, test/unittests/test_qfr_functionality.cpp
This PR addresses some bugs in the QFR optimization passes. In particular, the `removeFinalMeasurements` pass was not working as expected in some circumstances. Furthermore, some of the optimisation passes were not treating measurements and other non-unitary operations correctly.
=> Fix bugs in optimization passes

src/operations/StandardOperation.cpp, test/unittests/test_io.cpp
The `iSWAP`, `Peres` and `Peresdag` gates were exported with invalid OpenQASM caused by missing spaces when there are no control qubits.
A dump of an `iSWAP(0, 1)` gate previously looked as follows:
```qasm
swap q[0], q[1];
s q[0];
s q[1];
czq[0], q[1];
```
=> Fix iSWAP & Peres OpenQASM export

.github/workflows/deploy.yml, CMakeLists.txt, README.md, pyproject.toml, setup.py
This PR brings some minor improvements related to the CI/CD pipeline and Python packages:
- 🏗️ switch to PEP 517 `pyproject.toml`
- 🐛 🍎: deploying under macOS now produces fat binaries (i.e., for `x86_64` and `arm64` architectures). This allows to effectively build `universal2` wheels for Python 3.8 onwards and eventually makes the wheels work on M1-based Macs
- ⬆️ updated cibuildwheel to 2.3.0
- 🏗️ increase max CMake version to 3.22
- 🔖 increase version to 1.7.3
=> Minor Updates for CI/CD

src/CMakeLists.txt
Added a test in the CMakeLists.txt before adding the -march=native flag
The latest clang (clang-1300.0.29.30) on Apple M1 does not support it (yet?)
Depends on https://github.com/iic-jku/dd_package/pull/30 & submodule reference needs to be updated
=> Test for compiler flag -march=native

.github/workflows/deploy.yml, CMakeLists.txt, README.md, pyproject.toml, setup.py
This PR reverts the default behaviour of building universal binaries and, in turn, universal wheels for macOS.
The main reason for this is that universal wheels are hard to create once external dependencies are involved (see, e.g., iic-jku/qmap#16).
This PR also adopts a method that allows to infer the architecture to be used for compilation from the environment (thanks @katringoogoo).
=> 🍎 Revert to building separate instead of universal binaries and wheels

include/parsers/qasm_parser/Parser.hpp, include/parsers/qasm_parser/Token.hpp, src/parsers/QASMParser.cpp, src/parsers/qasm_parser/Parser.cpp, src/parsers/qasm_parser/Scanner.cpp, test/unittests/test_io.cpp
Up until now, reading a `.qasm` file that contains a `sx` or `sxdg` gate results in a `QuantumComputation` with a `CompoundOperation` that contains the decomposed gate sequence for these gates (e.g., `sdg - h - sdg` for `sx`).
This PR adds native support for these gates to the QFR `.qasm` parser.
As a result, `.qasm` files featuring these gates can be handled more directly.
=> ✨ add native support for `sx` and `sxdg` gates to qasm parser

include/QuantumComputation.hpp, src/QuantumComputation.cpp, test/unittests/test_io.cpp
This PR adds the functionality to add measurements according to the output permutation of a quantum circuit.
This is a first step towards realizing #35, in that it correctly conveys the expected output permutation in a standardized fashion.
Furthermore, this PR adds a convenience function to unify all quantum registers of a quantum circuit into a single register, which is useful for mapped circuits.
=> ✨ Measurements from output permutation

src/CMakeLists.txt
Fixes #124 by explicitly requesting the single header version of the nlohmann/json library.
=> Make Usage of Single Header JSON Lib Explicit

include/operations/OpType.hpp
This tiny little PR extends the `opTypeFromString` method to recognize more gates, e.g., recognize "cx" as `qc::OpType::X`. 
This helps when parsing instructions from Qiskit and matching them to the gates we provide.
=> 🚸 Extended Operation Recognition

mqt/qfr/qiskit/QuantumCircuit.hpp
This PR fixes a bug in the import of initial layout information from Qiskit that results in a segfault when trying to import a circuit containing layout information but not containing an ancillary register.
=> 🐛 Fix for Qiskit `Layout` import

src/CircuitOptimizer.cpp, test/unittests/test_qfr_functionality.cpp
This PR fixes a rare bug in the `cancelCNOTs` optimization that popped up in QMAP when a CNOT is followed by a SWAP and the SWAP's targets are not in sorted order. This resulted in an incorrect substitution of CNOTs.
=> 🐛 Fix bug in `cancelCNOTs` optimization

mqt/qfr/qiskit/QasmQobjExperiment.hpp, mqt/qfr/qiskit/QuantumCircuit.hpp
As of now, `reset` operations were not supported by the Qiskit circuit import. This PR adds the corresponding functionality.
=> ✨ support `reset` operations in Qiskit circuit import

src/CircuitOptimizer.cpp, src/QuantumComputation.cpp
The dynamic circuit transformation pass was not correctly handling `barrier` statements (leading to an endless loop).
Furthermore, the output permutation of a transformed circuit was messed up in some instances. This PR fixes both issues.
=> 🐛 Fix dynamic circuit transformation

include/QuantumComputation.hpp, src/QuantumComputation.cpp, test/unittests/test_qfr_functionality.cpp
This tiny PR adds a convenience function that allows to check whether a given logical qubit is present in the initial layout of a `QuantumComputation`.
=> 🚸 Check whether a logical qubit is contained in a circuit

src/QuantumComputation.cpp, test/unittests/test_qfr_functionality.cpp
This PR fixes an issue that, when an ancilla qubit is added to a quantum computation, the `ancillary` and `garbage` vectors are not appropriately resized.
=> 🐛  Fix ancillary and garbage tracking when adding ancilla qubits

mqt/qfr/qiskit/QuantumCircuit.hpp
The latest `qiskit-terra` update (`0.22.0`) changed the way the initial layout information is stored in quantum circuits. 
Instead of a plain `Layout`, it now uses a `TranspileLayout` dataclass (see https://github.com/Qiskit/qiskit-terra/pull/8802)
This PR adapts the corresponding import function to react to this change and provide a working solution across qiskit-terra versions.
In addition, it fixes a few linter warnings in the corresponding function.
=> 🐛⚡ Enable `qiskit-terra>=0.22.0` compatibility

CMakeLists.txt, mqt/qfr/CMakeLists.txt, mqt/qfr/bindings.cpp, pyproject.toml, setup.py
This PR modernizes the Python packaging in the QFR with the latest best practices.
=> ♻️📦 Modernize Python packaging

include/QuantumComputation.hpp, include/operations/CompoundOperation.hpp, include/operations/NonUnitaryOperation.hpp, include/operations/Operation.hpp, src/QuantumComputation.cpp, src/algorithms/QFT.cpp, src/algorithms/QPE.cpp, src/operations/NonUnitaryOperation.cpp, src/operations/Operation.cpp, test/unittests/test_qfr_functionality.cpp
This PR adds some convenience functions that allow easier creation of `QuantumComputation`s.
Specifically, a `QuantumComputation` can now be easily converted to an `Operation`. This allows one to create compound operations by first building a quantum circuit and, then, turning it into an operation.
Furthermore, a convenience function for adding classically-controlled operations to circuits is provided. This avoids the verbose code of having to create the quantum operation, constructing the ClassicControlled operation out of that, and then emplacing the resulting operation in the circuit.
Furthermore, it adds a method to determine the circuit depth.
Most of the changes here are actually in the tests, which have been refactored to take advantage of the new convenience features and, imho, …
=> ✨ Convenience features

.gitmodules, include/dd/FunctionalityConstruction.hpp, include/dd/NoiseFunctionality.hpp, include/dd/Operations.hpp, include/dd/Simulation.hpp, test/unittests/test_dd_noise_functionality.cpp
This PR builds on https://github.com/cda-tum/dd_package/pull/127 and refactors the DD template code.
None of the changes actually affect the performance or functionality of the code, but drastically improve IDE support.
=> 🚸 Better DD package templating

src/CMakeLists.txt
- Make nlohmann_json a system include to suppress potential warnings (see https://cmake.org/cmake/help/latest/prop_tgt/INTERFACE_SYSTEM_INCLUDE_DIRECTORIES.html for documentation)
=> Fixed a wrong property in CMake

src/QuantumComputation.cpp, test/unittests/test_io.cpp
This tiny little PR adds a barrier statement before adding measurements to the end of a circuit according to the output permutation. This allows for prettier printing and is more in line with what Qiskit is doing in the `measure_all` method.
=> 🚸 Add barrier before measurements

src/QuantumComputation.cpp
Simplifies the logic for how the output permutation is derived when importing circuits. Introduces a slight optimization where idle qubits are always marked as garbage; even when the qubit appears in the output permutation.
=> ♻️ Simplify output permutation computation in circuit import

src/operations/StandardOperation.cpp
The qelib1.inc file from OpenQASM contains the functions u3, cu3, u and cu (https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/qasm/libs/qelib1.inc). For this particular case, it is important to explicitly use the 3 parameter version, because cu has 4 parameters, while u only has 3 parameters.
So prepending c to the regular u gate leads to incorrect OpenQASM code, because then one parameter is missing (gamma).
=> 🐛 Fix controlled u-gate OpenQASM output

src/QuantumComputation.cpp, test/unittests/test_qfr_functionality.cpp
This PR fixes a small corner case that was overlooked when stripping idle qubits.
An idle qubit must not be removed from the circuit if the logical qubit is part of the output permutation.
=> 🩹 Fix strip idle qubits corner case

src/QuantumComputation.cpp
This is a quick fix that resolves the failures observed in the recent QMAP update. It allows to strip idle qubits from a circuit even if they are used in the output permutation, whenever the `force` flag is set.
=> 🩹 Allow removing logical qubits used in the output permutation by force

include/QuantumComputation.hpp, test/unittests/test_qfr_functionality.cpp
This PR introduces a `globalPhase` member in the QuantumComputation class that tracks the circuit's global phase.
Instead of appending an operation, the `qc.gphase(theta)` function now just adds to (and normalises) the phase of the circuit.
Previously, the Qiskit Circuit import would add an additional gate to every circuit. This already led to some problems in QMAP and is now resolved in a cleaner fashion, by just tracking the global phase.
=> ♻️ Refactor global phase handling

include/parsers/qasm_parser/Parser.hpp, src/QuantumComputation.cpp, test/unittests/test_qfr_functionality.cpp
If teleportation was used in mapping, add an opaque gate to the output.
=> Add opaque teleportation gate

.github/workflows/ci.yml
This tiny PR speeds up the CI by creating an independent job for collecting coverage instead of waiting for the linux build to finish.
=> 👷⚡ speed up CI with independent coverage job

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, CMakeLists.txt, cmake/Cache.cmake
This PR enables `ccache` integration for fast local as well as CI development.
Note: Caching under Windows does not yet work and will be investigated at a later point in time.
Thanks @marcelwa for the hint and the initial work towards setting this up in fiction 🙏🏼
=> 👨‍💻 introduce compiler cache

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml
This PR introduces [the `mold` linker](https://github.com/rui314/mold) as the default linker for Linux CI builds.
This should speed up the respective CI builds.
Thanks again to @marcelwa for the hint!
=> 👨‍💻 introduce `mold` as default linker under Linux

mqt/qfr/qiskit/QasmQobjExperiment.hpp
This PR fixes a bug where the parameters of parameterized gates are not saved when reading in circuits from `QasmQobjExperiments`. Previously the `params` list was always empty.
Related:
- cda-tum/ddsim#190
- cda-tum/ddsim#248
=> Actually Populate the Params list from Qobjs

src/CMakeLists.txt, src/python/qiskit/QasmQobjExperiment.cpp, src/python/qiskit/QuantumCircuit.cpp
Removes the additional include directories for `MQT::Core<...>` targets to avoid mixing headers with the same name.
See https://github.com/cda-tum/ddsim/pull/253#discussion_r1232225057 for why this might be necessary.
=> 🩹 avoid header confusion

src/python/CMakeLists.txt
This small PR makes it a little easier to get code completion for the C++-Python bindings.
Previously, it was rather hard to get CMake to find a Python-installed version of `nanobind`.
As a result, syntax highlighting and code completion did not work properly in the bindings code.
`scikit-build-core` automagically handles the location of the installed nanobind library by adding the module's CMake path to the CMake prefix path during the build.
This PR now automatically adds that CMake path even when not running via `pip install` by querying the Python interpreter that is required anyway.
So if you have `nanobind` installed in the current Python environment, it should now be correctly picked up without any manual workaround.
If it should happen that CMake picks up the wrong Python version, …
=> 🚸 Automatic discovery of nanobind when running outside `pip install`

CMakeLists.txt, cmake/CompilerOptions.cmake, pyproject.toml, src/CMakeLists.txt, src/dd/CMakeLists.txt, src/ecc/CMakeLists.txt, src/zx/CMakeLists.txt
This pull request moves the CMake code for building the targets for the different parts of mqt-core into their respective subfolders.
Also this PR renames the `BINDINGS` CMake variable such that it is consistent and distinguishable from the Bindings variable of other MQT projects.
=> Cmake structure

.pre-commit-config.yaml
This PR adds a new pre-commit check that allows running `ruff` also on Jupyter notebooks, which might come in really handy for documentation purposes.
=> ➕🪝 add new pre-commit hook for running ruff on Jupyter notebooks

include/dd/DDDefinitions.hpp, include/dd/Export.hpp, include/dd/Node.hpp, include/dd/NoiseFunctionality.hpp, include/dd/Operations.hpp, include/dd/Package.hpp, include/dd/StochasticNoiseOperationTable.hpp, include/dd/UniqueTable.hpp, src/dd/Edge.cpp, src/dd/FunctionalityConstruction.cpp, src/dd/Node.cpp, src/dd/Simulation.cpp, src/dd/UniqueTableStatistics.cpp, test/algorithms/eval_dynamic_circuits.cpp, test/algorithms/test_bernsteinvazirani.cpp, test/algorithms/test_entanglement.cpp, test/algorithms/test_grcs.cpp, test/algorithms/test_grover.cpp, test/algorithms/test_qft.cpp, test/algorithms/test_qpe.cpp, test/algorithms/test_random_clifford.cpp, test/dd/test_dd_functionality.cpp, test/dd/test_dd_noise_functionality.cpp, test/dd/test_package.cpp, test/unittests/test_ecc_functionality.cpp
This PR completely eliminates the static DD node terminals and replaces them by using `nullptr` instead.
For one, this eliminates some global static variables.. Yay 😃
Furthermore, DD terminal nodes are no longer associated with the index `-1`. This allows changing the qubit index to an unsigned type and unlocks double the number of qubits (while also allowing to get rid of some `static_cast`s).
Finally, analysis has shown that the DD node size does not increase when using 16 bits for the qubit index (due to alignment). Hence, the package now directly supports up to `65536` qubits 🥳.
Note that this, naturally, is a breaking change. Qubit indices are now unsigned and checks for a terminal node should now use the respective functions of the Node classes instead of relying the variable index …
=> ♻️ Eliminate DD terminal nodes

.clang-tidy, include/dd/UniqueTable.hpp
This PR disables the `NullDereference` clang-tidy check since it led to many false positives.
=> 🔧 Disable `NullDereference` clang-tidy check

include/dd/Package.hpp, test/dd/test_package.cpp
=> 🐛 Fix DD node leak

include/dd/ComputeTable.hpp, include/dd/Package.hpp, include/dd/UnaryComputeTable.hpp, test/dd/test_package.cpp
This PR fixes a regression in the compute table performance after #381.
Since terminals are no longer represented by separate entities the assumption that `e.p == nullptr` implies a lookup miss is no longer true. This PR adapts the corresponding places in the code to handle the changes properly.
=> 🐛 Fix Compute Table Performance

include/dd/FunctionalityConstruction.hpp, include/dd/Operations.hpp, include/operations/NonUnitaryOperation.hpp, include/operations/OpType.hpp, src/CircuitOptimizer.cpp, src/dd/Operations.cpp, src/operations/NonUnitaryOperation.cpp, src/parsers/QASMParser.cpp, test/unittests/test_qfr_functionality.cpp
Removed the parsing and creation of Snapshot and ShowProbabilities instructions from QASMParser and NonUnitaryOperations due to their irrelevance within MQT Core. This eliminates unnecessary error checking and streamlining the codebase. NonUnitaryOperation no longer needs to account for Snapshot and ShowProbabilities, simplifying its logic. The operations were also removed from related files and tests to maintain consistency.
=> 🔥 Remove Snapshot and ShowProbabilities instructions from MQT Core

include/CircuitOptimizer.hpp, include/QuantumComputation.hpp, include/operations/NonUnitaryOperation.hpp, include/operations/OpType.hpp, include/operations/Operation.hpp, src/CircuitOptimizer.cpp, src/QuantumComputation.cpp, src/operations/NonUnitaryOperation.cpp, src/operations/Operation.cpp, src/operations/StandardOperation.cpp, src/parsers/QASMParser.cpp, test/dd/test_dd_functionality.cpp
This commit refactors how the `Barrier` operations are handled across the operations, moving it from non-unitary operations to the standard operations. The changes include updates in the display of the barriers and how they are parsed in the QASMParser, along with modifications in the operation files and test files. This change improves code structure allowing a more consistent handling of operations. Barriers are essentially No-Ops, so there is no reason for them to be non-unitary.
=> ♻️ Refactor handling of Barrier operations

.github/workflows/reusable-change-detection.yml, .pre-commit-config.yaml, pyproject.toml
This PR enables the newly introduced target support of scikit-build-core. This should significantly speed-up the build process as it only builds the relevant CMake target and skips everything else.
=> 📦 Enable target support from scikit-build-core

include/operations/NonUnitaryOperation.hpp, src/operations/NonUnitaryOperation.cpp
In the NonUnitaryOperation class, the previous implementation used two different vectors to manage the targets for Measure and other operations, which lead to redundancy in the code. This update unifies the handling of targets by using only one vector (named targets) for all operations. This simplification enhances the code readability and maintainability. It also removes the need of several functions like getTargets() and getUsedQubits(). Several function argument lists have also been refactored for cleaner and more consistent usage. Further, the print() function was restructured for better clarity. Overall, these changes will be beneficial for future development work.
=> ♻️ Refactor `NonUnitaryOperation` class to simplify target handling

include/operations/Operation.hpp, test/dd/test_dd_functionality.cpp, test/unittests/test_qfr_functionality.cpp
Having `Barrier` operations report that they do not act on any qubits caused some problems upstream. This PR fixes the underlying issue and adds a test to prevent such errors in the future.
=> 🩹 Remove Barrier check from actsOn method

include/dd/Package.hpp, test/dd/test_package.cpp
The function ```makeDDFromMatrix``` incorrectly swaps the pointers for the second and third nodes in level 1 (2x2) input submatrices. This leads to a mismatch between the input and reconstructed matrices if the input matrix is not symmetrical. All the existing tests of this function don't contain a matrix where this problem would be visible. This PR contains two commits: The first one adds a new test to reproduce and show the problem, and the second one is the actual fix.
=> Fix makeDDFromMatrix Issue in Asymmetrical Matrices

include/operations/ClassicControlledOperation.hpp, include/operations/CompoundOperation.hpp, include/operations/NonUnitaryOperation.hpp, include/operations/Operation.hpp, include/operations/StandardOperation.hpp, include/operations/SymbolicOperation.hpp, src/CircuitOptimizer.cpp, src/operations/NonUnitaryOperation.cpp, test/unittests/test_qfr_functionality.cpp
This PR replaces the `setControls` function on `Operation` with `addControls` and `clearControls`.
Calling `clearControls` on `CompoundOperation`s will throw an Exception, since doing so is not possible at the moment (we don't know if a control was pushed down from a `CompoundOperation` or was there from the beginning.
=> Add `addControl`, `clearControls`, `removeControl` functions on Operation

include/operations/ClassicControlledOperation.hpp, include/operations/CompoundOperation.hpp, include/operations/NonUnitaryOperation.hpp, include/operations/Operation.hpp, include/operations/StandardOperation.hpp, include/operations/SymbolicOperation.hpp, src/operations/StandardOperation.cpp, src/operations/SymbolicOperation.cpp, test/unittests/test_qfr_functionality.cpp
Add an `invert` function to `Operation`. This mirrors the functionality of the [OpenQASM 3.0 `inv` modifier](https://openqasm.com/language/gates.html#inverse-modifier).
For Compound gates, this calls `invert` on each nested operation and reverses the order of the operations.
For Standard gates, this checks which type of gate is being inverted and handles each case.
=> Add invert functionality for quantum operations

include/operations/NonUnitaryOperation.hpp, test/unittests/test_qfr_functionality.cpp
This is a follow-up to #411 that fixes an oversight that was revealed by compiler warnings.
The `Operation` class actually defines two `getControls` methods and #411 provided an override for a mixture of both, but not the actual methods.
=> 🚨 fix compiler warnings for `getControls` override

include/dd/UniqueTable.hpp, src/dd/MemoryManager.cpp, src/dd/statistics/MemoryManagerStatistics.cpp, test/dd/test_complex.cpp
Another small follow-up to #419 that squashed another couple of quirks in the statistics tracking.
=> 🚸  Small corrections for statistics tracking

include/dd/Edge.hpp, include/dd/Node.hpp, include/dd/NoiseFunctionality.hpp, include/dd/Package.hpp, src/dd/Edge.cpp
Due to a typing issue, the code responsible for shortcutting DD multiplication upon encountering identity nodes was never actually compiled (it checked on `mCachedEdge` instead of on `mEdge`).
This PR addresses the underlying issue and furthermore aligns the code base a little more with what's to come in #358.
This speeds-up the test suite by roughly a factor of 2.
=> 🐛 Fix identity handling in DD multiplication

.github/workflows/reusable-code-ql-python.yml, .pre-commit-config.yaml, include/python/pybind11.hpp, noxfile.py, pyproject.toml, src/python/CMakeLists.txt, src/python/module.cpp
This PR moves the project back to pybind11 from nanobind.
While playing around, it turns out that nanobind is not yet mature enough and would require quite some workarounds to get working for everything.
Closes #344
=> ♻️ switch back from nanobind to pybind

src/python/qiskit/QuantumCircuit.cpp
This PR fixes the output permutation deduction in the Qiskit circuit import.
The underlying assumption in our tools is that if a circuit contains no measurements, the identity permutation shall be assumed.
However, when an initial layout is present in the input circuit, our methods would only deduce the initial layout and keep the output permutation untouched.
This resulted in a mismatch between the initial layout and the output permutation.
=> 🐛 Fix output permutation deduction

include/dd/DDpackageConfig.hpp, include/dd/Node.hpp, include/dd/Package.hpp, include/dd/statistics/PackageStatistics.hpp, test/dd/test_package.cpp
This PR removes the computation of the `isSymmetric` property in matrix DDs.
The corresponding check was conducted on every node creation in `makeDDNode` and the resulting property was only used as a shortcut in the `transpose` method.
However, the `transpose` method is not used anywhere in our codebase.
As a consequence, this PR also removes the `transpose` method to reduce the amount of code bloat in our code base.
Overall, this should yield a small net performance gain for every operation involving matrices.
=> ⚡ Skip `symmetry` computation and 🔥 remove `transpose` method

noxfile.py, pyproject.toml
This PR temporarily disables editable installs in the nox sessions to circumvent a bug that surfaced in the latest scikit-build-core version (>=0.6).
This should allow CI to pass again.
=> 🩹 temporarily disable editable installs in nox jobs

src/QuantumComputation.cpp, test/unittests/test_io.cpp
Removing the superfluous assertion in `QuantumComputation::dump(filename, format)`, that the file name needs to contain exactly 1 dot.
Instead, added an equivalent check (for >= 1 dot) in `QuantumComputation::dump(filename)`, where it is actually necessary.
Fixes #446
=> Fixing `QuantumComputation::dump` file name dot count check

include/dd/Complex.hpp, include/dd/ComplexNumbers.hpp, include/dd/Edge.hpp, include/dd/Export.hpp, include/dd/NoiseFunctionality.hpp, include/dd/Package.hpp, include/dd/RealNumber.hpp, include/dd/UniqueTable.hpp, src/dd/Complex.cpp, src/dd/ComplexNumbers.cpp, src/dd/Edge.cpp, src/dd/FunctionalityConstruction.cpp, src/dd/RealNumber.cpp, test/dd/test_complex.cpp, test/dd/test_edge_functionality.cpp, test/dd/test_package.cpp
This is the first in a series of small PRs that try to extract and break apart useful parts of #444.
It replaces the obnoxious static member variables we use for the complex `zero` and `one` as well es the `zero` and `one` terminals with `constexpr` methods of the respective classes.
This makes for a nicer overall interface and fewer reasons to add clang-tidy ignores.
=> ♻️ Replace static `zero` and `one` members with constexpr functions

src/dd/RealNumberUniqueTable.cpp
This PR slightly improves the lookup logic in the `RealNumberUniqueTable` to avoid a redundant check on zero for negative values.
Furthermore, it updates the statistics tracking code to only track actual lookups that did not result in one of the static constants.
It is another PR in the series of improvements coming from #444
=> ⚡ Small performance improvements to `RealNumberUniqueTable`

include/dd/CachedEdge.hpp, include/dd/Complex.hpp, include/dd/ComplexNumbers.hpp, include/dd/ComplexValue.hpp, include/dd/MemoryManager.hpp, include/dd/Package.hpp, src/dd/CachedEdge.cpp, src/dd/Complex.cpp, src/dd/ComplexNumbers.cpp, src/dd/ComplexValue.cpp, src/dd/MemoryManager.cpp, src/dd/Simulation.cpp, test/dd/test_complex.cpp
This PR is "just" another one in the series of bringing over improvements from #444.
This time it starts with the reduction of the complex cache being used by completely eliminating any temporary use of cache entries. This is enabled by extending the computation support and interoperability between `Complex` and `ComplexValue`.
=> ⚡ Completely eliminate temporary numbers borrowed from the cache

include/dd/Complex.hpp, src/dd/Complex.cpp, src/dd/ComplexNumbers.cpp
A further PR on the road to #444.
The change here has shown a noticeable impact on the stability of simulating Grover's algorithm.
On a 33-qubit Grover benchmark it resulted in roughly 200 vector and 16000 matrix nodes less.
=> ⚡ improve numerical accuracy of multiplication and division

src/CircuitOptimizer.cpp, test/unittests/test_qfr_functionality.cpp
This PR fixes a small bug in the single-qubit gate fusion optimisation method where repeated cancellations would lead to empty compound operations that were then directly accessed without checking whether there are actually elements to access.
=> 🐛 properly handle repeated cancellation in single-qubit gate fusion

include/dd/RealNumberUniqueTable.hpp, src/dd/RealNumberUniqueTable.cpp
This PR improves the logic for handling collisions in the unique table for real numbers.
Since we track tail pointers anyway, insertions in the back can be accomplished very cheaply.
This can be used in both lookup scenarios; the border case and the middle case.
If no match was found in a border case, it is clear that the new entry should either be added to the end of one or the beginning of the other bucket list.
In the standard case, one can first check whether the looked up value is larger (or equal) than the last element in the bucket.
If so, the new entry can just be added to the end of the collision chain.
In a 33-qubit Grover simulation this saved a couple million collisions.
=> ⚡ improved collision logic in `RealNumberUniqueTable`

src/dd/ComplexNumbers.cpp, src/dd/ComplexValue.cpp
The omission of some of the approximation checks (partly introduced in #458 and #457) has surfaced as a performance regression during recent testing.
This PR adds back the corresponding checks so that performance is on the expected level again.
=> ⚡ fix performance regression for `RealNumber` computations

pyproject.toml, test/python/test_qiskit.py
The newest Qiskit release introduced some new deprecations and, unfortunately, also some internal deprecation warnings that now surface in our tests and must be ignored.
This PR adjusts MQT Core to these latest changes.
=> 🚨 Adapt to latest Qiskit version

src/CircuitOptimizer.cpp, test/unittests/test_qfr_functionality.cpp
This PR addresses an issue in the circuit flattening pass where nested CompoundOperations were not handled properly and silently discarded operations.
This furthermore simplifies the implementation a little bit.
=> 🐛 Fix recursive circuit flattening

include/CircuitOptimizer.hpp, src/CircuitOptimizer.cpp, test/unittests/test_qfr_functionality.cpp
This PR adds a small new optimization routine that iterates over a circuit and replaces every occurrence of a (multi-)controlled X gate with a (multi-)controlled Z gate that is sandwiched by Hadamard gates on its target.
=> ✨ Circuit optimisation for replacing Toffoli gates with MCZ gates and Hadamards

include/dd/Package.hpp, test/dd/test_package.cpp
This PR fixes an issue in the `kronecker` method of the DD package where (for whatever reason) the situation where `x` contained a node where `x.p->isIdentity()` is true at some point was not handled properly and some edge weights were dropped.
Furthermore, this PR optimises the compute table lookup strategy similar to how this is done for simulation since the top edge weights can just be filtered out before the lookup and multiplied in the end before returning the result.
=> 🐛⚡ fix and speed up Kronecker product for DDs

include/QuantumComputation.hpp, src/QuantumComputation.cpp, src/mqt/core/plugins/qiskit.py, src/operations/NonUnitaryOperation.cpp, test/unittests/test_io.cpp
This PR brings some improvements and fixes to the handling of qubits and registers in MQT Core.
First of all, it fixes the routine that marks qubits as ancillaries so that qubits are really properly transformed from regular qubits in a regular register to ancillary qubits in an ancillary register.
Second, it improves the stability of the QASM dump by making sure that the registers are dumped in the proper order that they were declared in.
Lastly, it fixes an oversight in the routine for unifying registers that effectively erased any ancillary qubits from the qubit count.
=> 🐛 Miscellaneous fixes for qubit and register handling

src/python/operations/register_operation.cpp
For some reason, GCC 10 and older have a problem with the pybind11 way of automatically defining `operator==`, `operator!=` and `hash` when the class they are defined on is abstract.
Newer versions of GCC do not complain about this and just work.
This PR works around the underlying issue by defining the respective functions manually again.
=> 🐛 fix compiler errors in GCC-10 due to abstract return type

.github/workflows/reusable-python-linter.yml, .pre-commit-config.yaml
Even when pre-installing build dependencies, the `check-sdist` pre-commit check still is pretty slow and slows down developer experience. This PR just moves the corresponding check to the reusable CI workflows.
That way, it is still run and any problems with SDists can still be caught, but DX is faster again.
=> 🚚 move `check-sdist` from pre-commit to CI

src/QuantumComputation.cpp, test/unittests/test_io.cpp, test/unittests/test_qfr_functionality.cpp
This kind of supersedes #493 and provides an alternative, less intrusive version that properly handles ancillary qubits and marking qubits in existing registers as ancillaries.
It simply checks on the removal of a qubit from a `qreg` whether that qubit is marked as ancillary and correspondingly decrements the right qubit number counter. 
This has also been tested in QCEC to resolve the errors that were popping up over there.
=> ♻️ Revised qubit register handling

src/parsers/qasm3_parser/passes/ConstEvalPass.cpp, test/algorithms/test_wstate.cpp
One of the recently introduced tests (in #445) adjusted the DD package tolerance to trigger a potential error.
However, that test did not restore the tolerance to its prior setting.
At least locally, this has led to quite some strange errors of subsequent tests failing.
I am kind of puzzled that this hasn't led to any CI failures.
Anyway, this PR fixes the underlying issue by properly resetting the tolerance to its original value.
=> 🩹 properly reset tolerance in test

include/Definitions.hpp, include/operations/ClassicControlledOperation.hpp, include/parsers/qasm3_parser/Statement.hpp, include/parsers/qasm3_parser/passes/ConstEvalPass.hpp, src/CMakeLists.txt, src/operations/ClassicControlledOperation.cpp, src/parsers/QASM3Parser.cpp, src/parsers/qasm3_parser/Statement.cpp, src/parsers/qasm3_parser/passes/ConstEvalPass.cpp, test/unittests/test_qasm3_parser.cpp
This PR adds support for the `else` branch in `if` statements when parsing OpenQASM 3.0.
Example:
```qasm
if (c == 1) {
x q[1];
} else {
x q[0];
x q[1];
}
```
This is implemented by adding a second ClassicalControlledOperation to the Quantum Computation with a flipped condition.
When dumping the circuit above, the following is printed:
```qasm
if (c == 1) {
x q[1];
}
if (c != 1) {
x q[0];
x q[1];
}
```
=> ✨ Add support for OpenQASM 3.0 `else`

include/operations/Expression.hpp
clang-tidy v18 includes some new warnings that just landed in CLion. These revealed that the whole `Expression` file was using the `std::enable_if` pattern to realize SFINAE in the wrong fashion.
This PR adjusts for that deficiency.
=> 🚨 proper use of `std::enable_if` for SFINAE

include/dd/Edge.hpp, include/dd/Package.hpp, src/dd/Edge.cpp, test/dd/test_package.cpp
This PR is another one in the series of PRs towards shrinking #444 and better understanding where the main performance difference in that branch is coming from.
In that regard, this PR moves the normalization routines for DDs from the `Package.hpp` file to the `Edge.hpp` file.
Furthermore, it separates the routines and code paths for cached and non-cached normalization which reduces the overall branching in the code.
Last, but certainly not least, it optimizes all four of the normalization routines for their corresponding scenario with a special focus on numerical stability.
=> ♻️⚡ Refactor and fine-tune DD normalization

include/dd/CachedEdge.hpp, include/dd/ComplexNumbers.hpp, include/dd/ComplexValue.hpp, include/dd/Edge.hpp, include/dd/MemoryManager.hpp, include/dd/NoiseFunctionality.hpp, include/dd/Package.hpp, include/dd/statistics/PackageStatistics.hpp, src/dd/CachedEdge.cpp, src/dd/ComplexNumbers.cpp, src/dd/Edge.cpp, src/dd/MemoryManager.cpp, test/algorithms/test_grover.cpp, test/algorithms/test_qft.cpp, test/dd/test_complex.cpp, test/dd/test_dd_functionality.cpp, test/dd/test_package.cpp
This PR completely refactors the DD package to not rely on a separate complex cache and make better use of the `CachedEdge` data structure.
This saves a level of indirection in many cases and makes the overall package just a little simpler as it now clearly separates DDs with edge weights that are not yet in the complex unique table from those that are in there already.
=> ♻️ Remove complex cache

include/dd/Complex.hpp, include/dd/ComplexNumbers.hpp, include/dd/ComplexValue.hpp, include/dd/ComputeTable.hpp, include/dd/Export.hpp, include/dd/Package.hpp, include/dd/RealNumber.hpp, src/dd/Complex.cpp, src/dd/ComplexValue.cpp, src/dd/RealNumber.cpp, src/dd/RealNumberUniqueTable.cpp, src/dd/Simulation.cpp, test/dd/test_dd_functionality.cpp, test/dd/test_package.cpp
This is a follow-up PR to #444. That PR has shown that the approximation conducted as part of complex number arithmetic (multiplication and division) can lead to quite some unexpected results.
Whenever we compute something on complex numbers, the respective computation should be as accurate as possible and rounding should happen as late as possible to maintain maximum accuracy.
This PR completely removes the approximate special casing in the complex number arithmetic. Correspondingly, it adjusts the computation of the top edge weight in the multiplication routine to reuse the already computed `rWeight`.
Furthermore, it optimizes out some of the approximation calls throughout the package and provides more accurate complex number arithmetic.
=> ⚡ Improved accuracy in complex number arithmetic

include/zx/ZXDefinitions.hpp, test/zx/test_zx.cpp
While this may not solve the underlying issue in #503, it should at least resolve some part of it and maybe reveal further warnings. It also fixes one of the new clang-tidy warnings for reducing the size of the underlying data type of enums.
=> 🎨 provide `operator<<` overloads for scoped enums in ZX package

src/parsers/QASM3Parser.cpp, test/unittests/test_qasm3_parser.cpp
Output permutation and initial layout need to be applied after the circuit is parsed completely.
This fixes an issue where an output permutation is declared with less qubits than are used in the circuit.
```qasm
// i 0 2 1 3
// o 3 0
qubit[4] q;
```
Would result in an output permutation of
```
0: 1
1: 1
2: 2
3: 0
```
instead of
```
0: 1
3: 0
```
The issue is fixed by applying the output permutation after parsing the complete circuit.
=> Fix handling of output permutation and initial layout

include/CircuitOptimizer.hpp, include/dd/Package.hpp, include/dd/Simulation.hpp, src/CircuitOptimizer.cpp, src/QuantumComputation.cpp, src/algorithms/BernsteinVazirani.cpp, src/algorithms/QFT.cpp, src/algorithms/QPE.cpp, src/dd/Simulation.cpp, test/CMakeLists.txt, test/algorithms/eval_dynamic_circuits.cpp, test/algorithms/test_bernsteinvazirani.cpp, test/algorithms/test_qpe.cpp, test/unittests/circuit_optimizer/test_backpropagate_output_permutation.cpp
This PR introduces a new optimization pass that allows one to backpropagate a given output permutation to the initial layout of a circuit.
This can be useful in situations where the initial qubit layout is not perfectly known or constructible (such as for dynamic quantum circuits that have been transformed by substituting resets and deferring measurements).
The pass tries to find the initial layout that best matches the given output permutation while considering any SWAPs in the circuit. Qubits that are not part of the output permutation (i.e., garbage qubits) are assigned via an identity mapping (if possible) or arbitrarily to the first available location.
This also fixes a small bug where the output permutation of a circuit was incorrectly set after deferring measurements.
In addition …
=> ✨ New optimization pass: Backpropagate output permutation and better dynamic circuit support

.cirrus.yml
This small PR updates the `cibuildwheel` version used in Cirrus-CI to `2.16.2`.
=> ⬆️ update cibuildwheel version on Cirrus-CI

include/parsers/qasm3_parser/Exception.hpp
This PR fixes a bunch of compiler warnings that MSVC reports for the newly introduced OpenQASM3 exception types.
=> 🚨 fix warnings about exceptions that privately inherit from `std::exeption`

eval/eval_dd_package.cpp, include/dd/Benchmark.hpp, include/dd/UniqueTable.hpp, include/dd/statistics/PackageStatistics.hpp, include/dd/statistics/Statistics.hpp, include/python/pybind11.hpp, include/python/qiskit/QuantumCircuit.hpp, src/dd/statistics/MemoryManagerStatistics.cpp, src/dd/statistics/Statistics.cpp, src/dd/statistics/TableStatistics.cpp, src/dd/statistics/UniqueTableStatistics.cpp, src/python/operations/register_operation.cpp, src/python/symbolic/register_expression.cpp, test/algorithms/test_wstate.cpp, test/dd/test_complex.cpp, test/dd/test_dd_noise_functionality.cpp, test/dd/test_edge_functionality.cpp, test/dd/test_package.cpp, test/unittests/test_io.cpp, test/zx/test_expression.cpp, test/zx/test_rational.cpp, test/zx/test_simplify.cpp, test/zx/test_zx.cpp, test/zx/test_zx_functionality.cpp
This PR changes all includes of external dependencies that are shipped with the project to use double quotes instead of angle brackets. As a consequence, this should pick up the shipped versions first instead of the system ones.
Fixes #503
=> 🐛 avoid using system header includes for external dependencies

include/operations/StandardOperation.hpp, src/operations/StandardOperation.cpp, test/unittests/test_qasm3_parser.cpp
For builtin gates, print a `c` prefix instead of `ctrl @ gate`.
Before:
```qasm
ctrl @ x q0, q1;
ctrl(2) @ x q0, q1, q2;
ctrl(3) @ x q0, q1, q2, q3;
```
After:
```qasm
cx q0, q1;
ccx q0, q1, q2;
ctrl(3) @ x q0, q1, q2, q3;
```
Gates with negative controls, more controls than natively supported or non-supported gates are printed as before, with the `ctrl @ gate` notation.
Fixes #519
=> For builtin gates, print `c` prefix instead of `ctrl @ `

cmake/ExternalDependencies.cmake
This was triggered in QCEC as a random test failure and seems to be due to bugs in earlier versions of multiprecision. `1.80` was confirmed to work.
=> ⬆️ raise minimum required Boost version to 1.80

eval/eval_dd_package.cpp, include/dd/FunctionalityConstruction.hpp, include/dd/Operations.hpp, include/dd/Simulation.hpp, src/dd/Benchmark.cpp, src/dd/FunctionalityConstruction.cpp, src/dd/Operations.cpp, src/dd/Simulation.cpp, test/algorithms/eval_dynamic_circuits.cpp, test/algorithms/test_bernsteinvazirani.cpp, test/algorithms/test_grcs.cpp, test/algorithms/test_qft.cpp, test/algorithms/test_qpe.cpp, test/dd/test_dd_functionality.cpp, test/dd/test_dd_noise_functionality.cpp, test/unittests/test_ecc_functionality.cpp
High-level functions such as `simulate` should not assume anything about the ownership of the DD package instance they are using. They now work on a reference to a package instance instead of a unique pointer.
This makes the interfaces more generic and usable in more scenarios.
It's quite possible that I missed some places and there will be a follow-up to this.
However, the changes here are enough to make everything work upstream for a new feature in QCEC.
=> 🚸♻️ Improve the high-level DD package interfaces

include/dd/Package.hpp, test/dd/test_package.cpp
This PR fixes a bug in the ancillary reduction routine of the DD package where some edge weights were simply overwritten.
Additionally, it optimizes the implementation to rely on cached edge weights throughout the computation which should reduce the influence on the complex number table.
Fixes #505
=> 🐛 Fix and optimize reduction of ancillaries

include/dd/Package.hpp, test/dd/test_package.cpp
This is a follow-up to #524 that applies similar fixes and optimizations to the reduction of garbage qubits.
As in the original PR this fixes an underlying issue where some edge weights were silently overwritten and increases the performance by making use of cached computations.
=> 🐛 Fix and optimize reduction of garbage

src/parsers/QASM3Parser.cpp, test/unittests/test_qasm3_parser.cpp
This fixes a small regression in the new QASM parser where plain `mcx` statements were no longer accepted.
=> 🐛 fix missing `mcx` gate support in OpenQASM3 parser

CMakeLists.txt, cmake/ExternalDependencies.cmake, cmake/GetVersion.cmake, cmake/StandardProjectSettings.cmake, cmake/mqt-core-config.cmake.in, pyproject.toml, src/CMakeLists.txt, src/dd/CMakeLists.txt, src/ecc/CMakeLists.txt, src/mqt/core/__init__.py, src/mqt/core/__main__.py, src/mqt/core/commands.py, src/python/CMakeLists.txt, src/zx/CMakeLists.txt, test/python/test_cli.py
This PR sets up the project so that it can be installed properly.
As it is configured right now, this allows to install the `mqt-core` Python package and make the C++ project available via `find_package(mqt-core)` as long as the proper cmake directory is added to the search path.
The right directory can easily be determined via `python -m mqt.core --cmake_dir` (or via `mqt-core-cli --cmake_dir`).
You might be wondering what this is useful for. It allows us to only require a single source copy of mqt-core in top-level projects once we switch them to using the `mqt-core` Python package. Otherwise, we would need to maintain the submodule and the Python package in parallel.
While I expect this to require some follow ups once used in practice, I believe this is a solid start.
Fixes #504
=> ✨ Allow project installation

src/zx/CMakeLists.txt
This PR fixes a small oversight in #529 where one of the install instructions was not guarded properly. This should fix the issues observed in cda-tum/mqt-qcec#352.
=> 🩹 guard install instruction

include/mqt-core/python/qiskit/QuantumCircuit.hpp, src/CMakeLists.txt, src/python/qiskit/QuantumCircuit.cpp
As the integration of the mqt-core Python package into the top-level tools turned out to be a much lengthier process than imagined, this PR adds back the `MQT::CorePython` target that was previously used to read in Qiskit objects.
This should allow development in the top-level libraries to continue without waiting for the remaining issues with the Python package being resolved.
=> ⏪ add `MQT::CorePython` target back

pyproject.toml, test/python/test_io.py
This PR works around some newly introduced deprecation warnings in the latest Qiskit version.
=> 🚨 fix Qiskit 0.46.0 deprecation warnings

cmake/CompilerOptions.cmake, src/parsers/qasm3_parser/passes/ConstEvalPass.cpp, src/python/CMakeLists.txt
This PR brings in a couple code quality improvements discovered when working on #538.
=> 🎨  Misc. code quality improvements

include/mqt-core/operations/CompoundOperation.hpp, src/CMakeLists.txt, src/operations/CompoundOperation.cpp
This PR ensures that all the different `Operation` sub-classes get a corresponding `typeinfo` and `vtable` symbol in the compiled binaries. This is important for RTTI when using shared libraries and ensured that `dynamic_cast`s across library boundaries work as intended. Specifically, the `CompoundOperation` class was only defined in a header, which led to the omission of said information. This is fixed by creating a dedicated `.cpp` file and moving at least one definition there.
This was discovered while working on #538 in combination with mqt-ddsim.
=> 🐛 ensure typeinfo and vtable information is present for `CompoundOperation`

include/mqt-core/operations/Expression.hpp, test/zx/test_expression.cpp
Fix Arithmetic Issues when dividing or multiplying a `PiExpression` by a `double`.
Partially solves #486
=> 🐛 Fix `PiExpression` division and multiplication arithmetic

include/mqt-core/operations/Expression.hpp, include/mqt-core/zx/FunctionalityConstruction.hpp, src/zx/FunctionalityConstruction.cpp, test/zx/test_zx_functionality.cpp
This PR adds the last remaining unsupported gates to the ZX library.
In the process, it also introduces a new convenience function for integer division of parameter expressions that simplifies some code. In conjunction with #549, this also fixes #486.
Fixes #343
=> ✨ Add `XX-plus-YY` and `XX-minus-YY` gate support to ZX library

pyproject.toml, test/python/constraints.txt
This PR marks the official support of Qiskit 1.0 in mqt-core.
In order to avoid all kinds of ugly compatibility hacks, this PR also changes the minimum required Qiskit version to 1.0.
Since Qiskit has devoted themselves to following semantic versioning from now on out, this hopefully means fewer compatibility changes in the future.
=> ✨ Support for Qiskit 1.0

.pre-commit-config.yaml, docs/quickstart.ipynb
This PR updates the jupyter notebook cleaning pre-commit check to preserve MIME metadata. This allows to use raw RST cells within jupyter notebooks, which can be very helpful for using Sphinx references as part of the documentation.
=> 🚸 allow using raw RST cells in jupyter notebooks

include/mqt-core/dd/DDpackageConfig.hpp, include/mqt-core/dd/NoiseFunctionality.hpp, include/mqt-core/dd/UniqueTable.hpp, src/dd/FunctionalityConstruction.cpp, src/dd/NoiseFunctionality.cpp, test/dd/test_dd_noise_functionality.cpp
This PR contains a couple of fixes for the noise-aware simulation techniques currently being reworked in cda-tum/mqt-ddsim#321.
More precisely, this PR makes sure that the corresponding DD package configs are already defined in the mqt-core library and that explicit instantiations for the methods relevant for DDSIM are in place.
=> 🩹 fixes for noise-aware simulation in DDSIM

src/parsers/qasm3_parser/Scanner.cpp, test/unittests/test_qasm3_parser.cpp
This PR fixes a small bug in the QASM importer that would prevent it from properly importing floating point numbers in scientific notation.
=> 🐛 Fix scientific notation in QASM import

include/mqt-core/dd/DDpackageConfig.hpp, include/mqt-core/dd/Package.hpp, test/dd/test_package.cpp
This PR adds a convenience method for efficiently computing the complex conjugate of a vector decision diagram, i.e., a new decision diagram, where every amplitude is complex conjugated. This amounts to traversing the decision diagram and conjugating each edge weight. As such, it directly scales with the number of nodes in the decision diagram.
=> ✨ add method for computing the conjugate of a vector DD

include/mqt-core/dd/DDpackageConfig.hpp, include/mqt-core/dd/Package.hpp
This PR makes sure that the newly introduced magnitude addition function for decision diagrams is as configurable as the rest of the compute tables. Some package types clearly do not need the new functionality and can keep the respective compute table small.
Furthermore, the PR makes sure that the new compute tables are properly reset.
=> 🚸 Improved usability for new magnitude addition functionality

include/mqt-core/dd/ComputeTable.hpp
This PR fixes an easy to overlook bug in the compute table implementation. The check in the old implementation was never evaluating to true due to the types being used in the various compute tables.
This allowed matrix and density matrix nodes to me mixed because the subsequent condition was never checked.
This PR adjusts the condition so that the checks are evaluated for both, addition and multiplication of density matrices.
Note that this has quite some interesting consequences, where a density matrix can have two successors that have exactly the same structure, but are represented by different DDs due to one (0-successor) representing a density matrix and one (1-successor) representing a matrix. Although both successors have to represent diagonal matrices for this to occur.
=> 🐛 fix check for density matrices in compute tables

include/mqt-core/dd/Node.hpp, include/mqt-core/dd/Package.hpp, test/dd/test_dd_noise_functionality.cpp
This PR fixes #567 and should subsequently allow to fix cda-tum/mqt-ddsim#361, which is the final blocker for merging #358.
=> 🐛 Density matrix idenity handling

include/mqt-core/dd/Operations.hpp, include/mqt-core/dd/Package.hpp, test/dd/test_package.cpp
The second follow-up PRs to #358, which tries to simplify the underlying functions and methods for representing operations.
This PR specifically streamlines the `makeTwoQubitGateDD` method in the DD package and eliminates the `nqubits` and `start` parameters, which are no longer necessary.
=> ♻️ streamline `makeTwoQubitGateDD` method

src/dd/NoiseFunctionality.cpp, test/unittests/test_qfr_functionality.cpp
This small PR fixes a handful of compiler warnings that popped up during updating mqt-qmap.
=> 🚨 fix a couple of compiler warnings

include/mqt-core/CircuitOptimizer.hpp, src/CircuitOptimizer.cpp, test/unittests/circuit_optimizer/test_collect_blocks.cpp, test/unittests/circuit_optimizer/test_reorder_operations.cpp, test/unittests/test_qfr_functionality.cpp
This PR adds a new optimization pass to the `CircuitOptimizer` which allows to collect blocks of gates acting on a certain number of qubits.
This is heavily inspired by Qiskit's [`CollectMultiQubitBlocks`](https://docs.quantum.ibm.com/api/qiskit/qiskit.transpiler.passes.CollectMultiQBlocks).
Operations are greedily grouped together, and blocks of gates are replaced by compound operations.
This optimization could be useful for QMAP to decrease the number of two-qubit gates in a circuit.
It could also be useful for QCEC since it allows to combine multiple small operations at once before applying them to the decision diagram.
=> ✨ Collect blocks optimization

include/mqt-core/operations/CompoundOperation.hpp, src/CircuitOptimizer.cpp, src/operations/CompoundOperation.cpp, test/unittests/circuit_optimizer/test_collect_blocks.cpp
This PR slightly optimizes the implementation of the `collectBlocks` optimization pass introduced in #581.
=> ♻️⚡ optimize implementation of `collectBlocks`

include/mqt-core/CircuitOptimizer.hpp, src/CircuitOptimizer.cpp
This PR internalizes all the private/protected methods in the circuit optimizer.
There is hardly any use in exposing them, so it's fine to just define them in the source file.
=> ♻️ internalize private methods of the circuit optimizer

include/mqt-core/CircuitOptimizer.hpp, include/mqt-core/operations/CompoundOperation.hpp, include/mqt-core/operations/Control.hpp, include/mqt-core/operations/NonUnitaryOperation.hpp, include/mqt-core/operations/Operation.hpp, src/CircuitOptimizer.cpp, src/QuantumComputation.cpp, src/operations/CompoundOperation.cpp, src/operations/NonUnitaryOperation.cpp, src/operations/Operation.cpp, src/parsers/QCParser.cpp, test/unittests/circuit_optimizer/test_elide_permutations.cpp
This PR introduces a new optimization that allows to elide permutations from circuits.
Essentially, it starts with the initial layout, applies it to every gate of the circuit. 
Upon encountering a `SWAP` gate, the tracked permutation is updated and the gate eliminated.
Finally, the output permutation of the circuit is updated.
The PR also includes some fixes for newer clang-tidy warnings as well as a small printing fix for quantum circuits.
=> ✨ Elide permutations optimization

.github/workflows/reusable-python-ci.yml
This PR simplifies the CI pipeline a little by combining two jobs into one and, as a consequence, saving one runner that has to spin up just to run a single command.
=> ♻️ simplify reusable Python CI workflow

include/mqt-core/Permutation.hpp, include/mqt-core/operations/Control.hpp, src/mqt/core/_core/__init__.pyi, src/mqt/core/_core/operations.pyi, src/mqt/core/_core/symbolic.pyi, src/python/operations/register_control.cpp, src/python/register_permutation.cpp
This PR brings some small improvements to the bindings of the `Control` and `Permutation` classes.
In particular, it adds hashing support and as well as equality comparisons.
For the `Permutation` class, it also adds an implicit conversion to a Python dictionary and fixes the Python stubs to include the constructor of the class.
This was inspired by #592 and helps to simplify some of the tests there.
=> 🚸 small improvements to `Control` and `Permutation` bindings

src/QuantumComputation.cpp, src/mqt/core/plugins/qiskit.py, test/python/test_qiskit.py, test/unittests/test_qfr_functionality.cpp
This PR adds support for Qiskit's `final_layout` attribute when importing circuits from Qiskit. It interprets the `output_permutation` of an MQT `QuantumComputation` object based on Qiskit's `final_index_layout()`, which maps the original input circuit's qubit indices to the final physical qubit indices after routing. This mapping is the result of applying `routing_permutation()` to the `initial_layout`. Additionally, it fixes the interpretation of the output_permutation in `initializeIOMapping()` to align with Qiskit's final_layout.
Fixes #439
=> :sparkles: Support for Qiskit's final_layout

.github/codecov.yml, .github/workflows/reusable-python-ci.yml
GitHub's `macos-14` runners now also support Python 3.8 and 3.9. This PR adjusts the reusable workflows to remove the special handling that was in place previously.
=> 👷🔧🍎 enable Python 3.8+ tests on macos-14 runners

README.md
This PR changes the path from which the images for the readme are gathered to the MQT repository.
In the long run, this will allow us to remove these files from the repositories themselves and only maintain a single copy of them.
In a follow-up, the links in the RtD documentation will be adapted accordingly. 
=> 🍱  Use centralized images from MQT repository

.github/codecov.yml, .github/workflows/cd.yml, .github/workflows/ci.yml
This PR switches to the new coverage collection workflow proposed in https://github.com/cda-tum/mqt-workflows/pull/2. The workflow now aggregates all coverage reports on the GitHub side before uploading to Codecov. It also uses Codecov's OIDC instead of TOKEN upload.
=> 🧱 switch to new coverage collection workflows

include/mqt-core/na/NADefinitions.hpp, include/mqt-core/operations/AodOperation.hpp, src/operations/AodOperation.cpp, test/na/test_nadefinitions.cpp, test/test_operation.cpp
This changes the namespace of the recently introduced AodOperations to be consistent with QMAP.
It also adds two methods to the Point class of @ystade which are required by the Hybrid Mapper.
=> Change namespace to na and extend Point class

include/mqt-core/parsers/qasm3_parser/Exception.hpp, include/mqt-core/parsers/qasm3_parser/Parser.hpp, include/mqt-core/parsers/qasm3_parser/passes/ConstEvalPass.hpp, include/mqt-core/parsers/qasm3_parser/passes/TypeCheckPass.hpp, src/parsers/QASM3Parser.cpp, test/unittests/test_qasm3_parser.cpp
This PR augments the QASM parser exceptions with a proper overload of the `std::exception::what()` method so that they print proper error messages when raised. This came up in the light of https://github.com/cda-tum/mqt-ddvis/issues/259
=> 🚸 Better QASM parser exceptions

include/mqt-core/datastructures/SymmetricMatrix.hpp, test/datastructures/test_symmetric_matrix.cpp
Moved the datastructure "Symmtric Matrix" from qmap to mqt-core as it might be useful also in other situations.
=> Moved symmetric matrix to datastructures

cmake/PackageAddTest.cmake
This tiny PR adds a new macro for explicitly setting the working directory for a googletest test suite. This can be useful for ensuring that files on the system are properly found in the tests.
=> 🚸 new test macro with customizable working directory

include/mqt-core/CircuitOptimizer.hpp, src/CircuitOptimizer.cpp, test/unittests/test_qfr_functionality.cpp
To not only remove Identities but also other Operations I wrote a function that generalizes that concept and allows one to remove arbitrary operation types.
=> Generalize concept of removing OpTypes

src/CMakeLists.txt
This PR adds an Export Header (see https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html) that can be used to manage symbol visibility. This PR does not make use of that feature yet, but can be seen as a preparation towards properly building shared libraries for this project.
=> ✨ add an export header to explicitly manage symbol visibility

include/mqt-core/Permutation.hpp, include/mqt-core/na/NAComputation.hpp, include/mqt-core/na/NADefinitions.hpp, include/mqt-core/na/operations/NAGlobalOperation.hpp, include/mqt-core/operations/CompoundOperation.hpp, include/mqt-core/operations/NonUnitaryOperation.hpp, include/mqt-core/operations/Operation.hpp, src/na/NAComputation.cpp, src/na/operations/NALocalOperation.cpp, src/operations/CompoundOperation.cpp, src/operations/Operation.cpp, test/datastructures/test_layer.cpp, test/na/test_nacomputation.cpp, test/na/test_naoperation.cpp, test/test_operation.cpp, test/unittests/test_qfr_functionality.cpp
This PR contains modifications that were necessary for the tests of the Neutral Atom Logical Array Compiler, see cda-tum/mqt-qmap#470.
=> 🚸 Support for adding tests to NALAC

.github/workflows/cd.yml, .github/workflows/ci.yml, .pre-commit-config.yaml, pyproject.toml
This PR makes use of `cibuildwheel`'s latest addition of a `build[uv]` build frontend option that uses `uv` under the hood to speed up the build process.
Furthermore, it adjusts the Windows repair command to respect namespace packages.
Before and after:
| | Before | After | Improvement |
| Overall Usage | 7h 37m 44s | 6h 53m 29s | -44min |
=> ⚡🔧  Faster `cibuildwheel` and better Windows wheel repair

include/mqt-core/dd/DDpackageConfig.hpp, include/mqt-core/dd/Package.hpp, test/dd/test_package.cpp
This PR introduces improvements for the trace computation: 
1. Adds a compute table for storing results of eliminated nodes during (partial) trace computation
- this allows the full trace computation to scale linearly with the number of nodes
- however, the partial trace computation still scales with the number of paths in the DD if the bottom qubits are to be eliminated:  non-eliminated nodes cannot be stored in the compute table, as this would prevent their proper elimination in subsequent trace calls
2. Normalizes the result
Fixes #336
=> Improvements for Trace Computation

include/mqt-core/parsers/qasm3_parser/StdGates.hpp, test/test_operation.cpp, test/unittests/test_qasm3_parser.cpp
🚧 Should probably have opened an issue but I wanted to directly add the failing test.
I downloaded a circuit for AE with 2 qubits compiled hardware-agnostically with qiskit from MQT Bench and inserted this circuit as input to `qc::QuantumComputation::fromQASM()`, which should not throw an error but it does, see the respective test 
https://github.com/cda-tum/mqt-core/blob/f91a0526617dbb68e2ce3589a8994f220bc44347/test/test_operation.cpp#L263-L287
=> 🐛 Support `u` gate when parsing OpenQASM 2

include/mqt-core/dd/Benchmark.hpp, include/mqt-core/dd/Operations.hpp, include/mqt-core/dd/Package.hpp, src/dd/FunctionalityConstruction.cpp, src/dd/Simulation.cpp, test/algorithms/eval_dynamic_circuits.cpp, test/algorithms/test_entanglement.cpp, test/algorithms/test_grover.cpp, test/algorithms/test_qpe.cpp, test/algorithms/test_random_clifford.cpp
This PR slighlty improves the usability of the IWYU features of clang-tidy for the DD package. To this end, it marks the `dd/Package_fwd.hpp` include in the `dd/Package.hpp` header as an export. This way, header need not include both headers, but can only import the `dd/Package.hpp` header to also get the content of the foward declaration header.
=> 🚸 make `dd/Package.hpp` export `dd/Package_fwd.hpp`

include/mqt-core/operations/AodOperation.hpp
This fixes a small erroneous cast in the `AodOperation` class that could potentially cause compilation errors on some systems.
=> 🩹 fix erroneous cast in `AodOperation`

include/mqt-core/CircuitOptimizer.hpp, include/mqt-core/operations/CompoundOperation.hpp, src/CircuitOptimizer.cpp, src/operations/CompoundOperation.cpp, src/parsers/QASM3Parser.cpp, test/unittests/test_qfr_functionality.cpp
This pull request adds the `customGate` flag to the `CompoundOperation` class. This flag is set for `CompoundOperations` that were constructed from custom gate calls.
The pull request also provides new functionality to the `flattenOperations` optimizer. Now, a second parameter can be used to indicate that only custom gates should be flattened. It makes sense to put this functionality here as outside of the `CircuitOptimizer` class, certain protected members cannot be accessed anymore.
=> :sparkles: Add `customGate` flag and optimizer functionality to flatten only custom gates

include/mqt-core/datastructures/UndirectedGraph.hpp, src/datastructures/Layer.cpp, test/datastructures/test_undirected_graph.cpp
Previously, the [`Layer.hpp`](https://github.com/cda-tum/mqt-core/blob/main/include/mqt-core/datastructures/Layer.hpp) class implicitly assumed that the circuit is fully reduced, i.e., redundant gates are removed. The new behaviour is to create new layer group for a gate that is already present in the current group, i.e., to handle them in the same way as they would not commute with the current group. Hence, every gate in a group is unique with respect its type and the qubits it is operating on.
=> Layer: Allow Redundant Gates

include/mqt-core/datastructures/Layer.hpp, src/datastructures/Layer.cpp, test/datastructures/test_layer.cpp
This adds minor changes required for the PR #500 in MQT QMAP.
=> Support for Neutral Atom State Preparation

src/mqt/core/load.py
This PR provides a convenient type that summarizes the default circuit inputs to the `load` method.
Special care is taken that this type is only defined in type checking environments and does not require importing optional dependencies that might not be available at runtime (such as qiskit).
=> 🏷️ providing a convenient `CircuitInputType`

.github/workflows/cd.yml, .github/workflows/ci.yml, pyproject.toml
This PR updates the MQT workflows to `v1.3`, which is the first version to offer moving minor tags that should reduce the update frequency.
Furthermore, the updated workflows combine the emulated wheel jobs to reduce overall build time and reduce the number of parallel jobs.
=> ⬆️ update mqt-workflows to v1.3 (moving tag)

cmake/ExternalDependencies.cmake, include/mqt-core/ir/operations/CompoundOperation.hpp, src/ir/parsers/QASM3Parser.cpp
This PR pulls out a couple of changes from #662 that can go into the library immediately, while that PR is still in draft.
Mostly fixes a couple of linter/compiler warnings and improves the handling of Boost / boost_multiprecision.
=> ♻️ miscellaneous changes pulled from #622

eval/CMakeLists.txt, noxfile.py, src/algorithms/CMakeLists.txt, test/circuit_optimizer/CMakeLists.txt
This PR is a follow-up to #668 and renames the `MQT::CoreAlgo` target (and associated concepts) to `MQT::CoreAlgorithms` to also match the corresponding folder name.
It also slightly adjusts the noxfile to make sure that the local package is always rebuilt.
=> 🚸 rename algorithms target and adapt nox config

pyproject.toml, src/mqt/core/plugins/qiskit.py, src/python/qiskit/QuantumCircuit.cpp, test/python/test_qiskit.py
Fixes all the deprecation warnings raised by Qiskit 1.2.
A warning filter still has to be applied since Qiskit itself imports deprecated code on the default path. This should be fixed in a follow-up release.
=> 🚨 fix Qiskit 1.2 deprecation warnings

cmake/ExternalDependencies.cmake, noxfile.py, pyproject.toml
This small PR updates the requirement on pybind11 to `2.13.5` which contains a fix for some relative paths that could trip up compilers.
=> ⬆️ require `pybind11 >= 2.13.5`

src/mqt/core/__init__.py, test/python/test_load.py
This PR fixes a small oversight in the `mqt.core.load` method, where the method would not work if being passed a `PathLike` object that is not a string (e.g., a `Path`).
The changes in the PR make sure that such an object is appropriately converted to a string before being passed to the constructor.
=> 🩹fix loading circuits from `PathLike` objects

.github/workflows/cd.yml, pyproject.toml
CentOS 7, which the default `manylinux2014` image is based on, reached end-of-life in June 2024. 
The only meaningful platforms left that do not provide a recent enough `glibc` version are some `Amazon Linux 2` platforms, which are not really relevant for the MQT.
This PR moves the Linux wheel builds to the more recent `manylinux_2_28` images, which offers many performance improvements and optimizations.
=> 🐍⬆️ update image for Linux wheel builds to `manylinux_2_28`

.pre-commit-config.yaml, CMakeLists.txt, pyproject.toml, src/circuit_optimizer/CircuitOptimizer.cpp
This PR contains a couple of assorted library improvements including touch ups on the CMake config, the mypy configuration, and the pre-commit hooks.
=> 🚸 Small library improvements

CMakeLists.txt, README.md, docs/installation.md, noxfile.py, pyproject.toml, src/mqt/core/plugins/qiskit.py
Python 3.8 will reach end of live in October 2024.
Qiskit is already issuing deprecation warnings since a couple of releases when using it on Python 3.8.
This PR officially drops support for Python 3.8 in mqt-core.
=> 🔥 drop Python 3.8 support

include/mqt-core/circuit_optimizer/CircuitOptimizer.hpp, src/circuit_optimizer/CircuitOptimizer.cpp, test/circuit_optimizer/test_defer_measurements.cpp
The previous implementation of the `isDynamicCircuit` check would falsely report a circuit to not be dynamic if the circuit contains multiple measurements on one qubit.
This PR fixes the underlying error and refactors the logic of the respective method to handle more cases.
This was discovered while working on https://github.com/cda-tum/mqt-qcec/issues/439
=> 🐛 Fix dynamic circuit detection

include/mqt-core/circuit_optimizer/CircuitOptimizer.hpp, include/mqt-core/ir/QuantumComputation.hpp, src/circuit_optimizer/CircuitOptimizer.cpp, src/ir/QuantumComputation.cpp, test/algorithms/CMakeLists.txt, test/circuit_optimizer/test_defer_measurements.cpp, test/circuit_optimizer/test_eliminate_resets.cpp, test/ir/test_qfr_functionality.cpp
This PR optimizes the `isDynamic`(Circuit) check by simplifying the overall implementation and making the function `const`.
Furthermore, the function is moved from the `CircuitOptimizer` to the `QuantumComputation` class itself.
Last, but not least, this PR fixes an issue in the CMake configuration that would prevent the algorithm tests to run properly.
=> ♻️ optimize `isDynamic` check and move to `QuantumComputation` class

include/mqt-core/ir/Permutation.hpp, include/mqt-core/ir/QuantumComputation.hpp, src/ir/Permutation.cpp, src/ir/QuantumComputation.cpp, test/ir/test_io.cpp, test/ir/test_qfr_functionality.cpp
This PR adds functionality to construct circuits from compound operations. 
In the process, it also improves the QASM dumping functionality by making it `const`.
Last, but not least, it refactors the corresponding IO tests to use more convenient interfaces that are now available.
Fixes #600
=> 🚸 Allow creating circuits from compound operations

.github/workflows/cd.yml, .github/workflows/ci.yml, noxfile.py, pyproject.toml, uv.lock
This PR updates the MQT workflows to their latest version.
These updates bring even more integration with `uv` to speed up the workflows and some refactoring in the Python testing workflow.
=> ⬆️  update MQT workflows to `v1.4`

src/ir/parsers/qasm3_parser/Parser.cpp, test/ir/test_qasm3_parser.cpp
This PR fixes an endless loop in the OpenQASM parser upon encountering unexpected statements in gate declarations.
WIth this PR, the parser actually errors out with an appropriate error message instead of looping forever.
=> 🩹 fix endless loop on unsupported operations in OpenQASM gate declarations

.github/workflows/cd.yml, .github/workflows/ci.yml, pyproject.toml
This PR updates the CD workflow so that anytime it runs on a push to `main`, it uploads the resulting package to Test PyPI. This allows to battle test the packages before official releases.
This will be especially important in the context of #662.
=> ⚗️ upload to Test PyPI for pushes on `main`

.github/workflows/cd.yml, .github/workflows/ci.yml
A small follow-up PR to #666 that adjusts how the continuous deployment job is run.
Hopefully, after merging, this allows to continuously upload to TestPyPI.
=> 🔧 adjust how the CD workflow is run

noxfile.py, pyproject.toml
This small PR moves the `--reinstall-package` configuration from the `noxfile` to the `tool.uv` table in the `pyproject.toml` file. This makes the `noxfile` a little more `uv` agnostic and simplifies the overall configuration.
=> ♻️ move `--reinstall-package` from `noxfile` to `pyproject.toml` configuration

.readthedocs.yaml
This PR makes sure that the virtual environment in the RtD build is activated so that the installed console-scripts become available.
=> 🩹 make sure to activate the venv in RtD build

noxfile.py, pyproject.toml
Revert to using separate build directories for the Python builds and rather rely on the caching performance of ccache between builds.
=> 🔧 use separate build directories per Python version

include/mqt-core/ir/parsers/qasm3_parser/Scanner.hpp, include/mqt-core/ir/parsers/qasm3_parser/Token.hpp, src/ir/parsers/qasm3_parser/Parser.cpp, src/ir/parsers/qasm3_parser/Scanner.cpp, src/mqt/core/__init__.py, test/ir/test_qasm3_parser.cpp
This PR fixes a bug in the QASM parser that would treat timing literal suffixes as individual tokens, which can lead to strange errors with gate declarations whose name matches a timing literal suffix, e.g., `ms`.
Timing literals are now properly treated and do not lead to clashes.
In the process, it was noticed that the Python import of long QASM strings would fail due to pathlib throwing an `OSError` for too long paths.
This is now fixed by short circuiting if the path is too long.
Fixes #723
=> 🐛 properly handle timing literals in QASM parser 

include/mqt-core/dd/GateMatrixDefinitions.hpp, test/dd/test_package.cpp
This has been brought up as in cda-tum/mqt-qcec/issues/489.
Turns out the endianness of the DCX gate matrix was wrong and this has not been detected because the tests where multiplying the gates of the definition for verification purposes in the wrong order.
After adjusting the tests, another incorrect endianness result popped up for the `xx_minus_yy` gate.
Both issues have now been fixed.
=> 🐛 fix endianness in DCX and XX_minus_YY gate matrix definition 

include/mqt-core/ir/QuantumComputation.hpp, src/zx/Utils.cpp, test/ir/test_qfr_functionality.cpp, test/zx/test_simplify.cpp
This PR fixes an out-of-bounds error in the ZX packages `EdgeIterator` that would happen whenever a ZX diagram would only consist of eliminated nodes.
In addition, this PR fixes an oversight in the QuantumComputation constructor where an empty qubit register `"q"` was added even on a zero-qubit circuit.
=> 🐛 Fix out-of-bounds error in ZX `EdgeIterator` and needless dummy register in empty circuit construction

.clang-tidy, eval/eval_dd_package.cpp, include/mqt-core/dd/Operations.hpp, include/mqt-core/dd/Package.hpp, include/mqt-core/dd/Simulation.hpp, include/mqt-core/ir/QuantumComputation.hpp, include/mqt-core/ir/operations/ClassicControlledOperation.hpp, pyproject.toml, src/algorithms/QFT.cpp, src/algorithms/QPE.cpp, src/dd/FunctionalityConstruction.cpp, src/dd/Simulation.cpp, src/mqt/core/ir/__init__.pyi, src/mqt/core/ir/operations.pyi, src/python/ir/operations/register_classic_controlled_operation.cpp, src/python/ir/register_quantum_computation.cpp, test/algorithms/test_bernsteinvazirani.cpp, test/algorithms/test_entanglement.cpp, test/algorithms/test_grover.cpp, test/algorithms/test_qft.cpp, test/algorithms/test_qpe.cpp, test/algorithms/test_random_clifford.cpp, test/algorithms/test_wstate.cpp, test/dd/test_dd_functionality.cpp, test/dd/test_dd_noise_functionality.cpp, test/dd/test_edge_functionality.cpp, test/dd/test_package.cpp
This pull request includes several changes aimed at improving code efficiency and readability across the DD package. 
* Introduced new utility functions in `Operations.hpp` for applying unitary operations, measurements, resets, and classically controlled operations on quantum states.
* DD routines for state preparation now automatically increase the respective refcount, so this does not have to be done manually anymore.
* The classic-controlled Operation class now exposes its comparison kind to the QuantumComputation class and to Python.
* Simplified the `getDD` function by removing redundant checks and improving the handling of permutations.
* A `sample` method was introduced as a shortcut for simply sampling from the output distribution of a circuit.
* Several tests were simplified and …
=> 🚸♻️ convenience methods and updates for DD functionality

pyproject.toml, uv.lock
This PR handles the new warnings popping up as a result of QIskit's 1.3 release.
This unblocks CI again.
=> 🚨 adapt to warnings related to Qiskit 1.3

pyproject.toml, uv.lock
This PR slighlty simplifies the dependencies setup after the recent `uv` update which automatically picks newer versions for newer Python versions. This allows simplifying the configuration for some of our dependencies.
The pandas lower bound in the test dependencies cannot be dropped yet as `uv` still picks an old pandas version without wheels for Python 3.13 when resolving for minimum versions.
=> ➖ simplify dependencies after `uv` update

src/mqt/core/__init__.py, src/mqt/core/plugins/qiskit.py, test/python/test_load.py, test/python/test_qiskit.py
This PR slightly adjusts how the optional qiskit dependency is handled in the `load` method.
At that point in the function, the user is passing in a Qiskit `QuantumCircuit` anyway, so Qiskit will naturally be available.
An observation I had while working on this:
We currently do not enforce a particular version constraint on qiskit at runtime.
Thus, someone might use a version of qiskit that is too old at runtime, and will probably run into errors.
We could probably do a better job of suggesting people to install the `mqt.core[qiskit]` extra to guarantee compatibility.
=> 🚸 slightly tweak how optional qiskit dependency is handled

pyproject.toml, uv.lock
The latest update to `uv` adds proper support for packages managed by `setuptools-scm`.
Version information for packages with dynamic versioning is now not explicitly included in the lock file.
=> 🔒 update to latest `uv` version that properly supports dynamically versioned packages

src/ir/QuantumComputation.cpp, test/ir/test_qfr_functionality.cpp
Fixes #729
This PR builds on the register handling improvements in #807 and fixes the the last remaining part of the problem observed in #729.
When dumping a circuit to QASM that has been stripped of idle qubits, the initial layout and output permutation need to be adjusted so that the resulting circuit can be read in again without problems.
The reason this PR is so small is mainly because a lot of the legwork was already done in #807.
=> 🐛 Fix stripping of idle qubits

src/circuit_optimizer/CircuitOptimizer.cpp
This fixes a small bug observed as part of #803, which only surfaced on Windows in Debug mode when compiling using Clang 🤯 
Part of the block collection code in the circuit optimizer would invalidate an iterator due to an update of the respective container being iterated over within the loop.
=> 🐛 do not invalidate iterator in block collection

include/mqt-core/ir/parsers/qasm3_parser/passes/ConstEvalPass.hpp, test/ir/test_qfr_functionality.cpp
This PR fixes another small bug observed as part of #803, which only surfaced under macOS when using GCC as the compiler.
Turns out that GitHub's CodeQL was right after all and exact equality checks on floating point values can come back to bite you.
In this case, two computations of `std::tan(1.0)` resulted in values that were off by a single ULP.
Although I am not 100% certain how this can even happen, this PR works around any such errors by using a fuzzy floating point comparison with an epsilon on the order of `10-12`.
=> 🐛 use fuzzy comparison for floating point in const evaluation equality check

src/ir/QuantumComputation.cpp, test/ir/test_io.cpp
This PR fixes an oversight in #753 where the respective changes would sometimes create invalid output permutation dumps.
This surfaced as part of https://github.com/cda-tum/mqt-qmap/pull/418.
=> 🐛 fix permutation handling in QASM dump

include/mqt-core/qasm3/Importer.hpp, include/mqt-core/qasm3/InstVisitor.hpp, include/mqt-core/qasm3/Parser.hpp, include/mqt-core/qasm3/Statement.hpp, include/mqt-core/qasm3/Statement_fwd.hpp, include/mqt-core/qasm3/Types.hpp, include/mqt-core/qasm3/passes/ConstEvalPass.hpp, include/mqt-core/qasm3/passes/TypeCheckPass.hpp, src/ir/operations/ClassicControlledOperation.cpp, src/qasm3/Importer.cpp, src/qasm3/Parser.cpp, src/qasm3/passes/ConstEvalPass.cpp, src/qasm3/passes/TypeCheckPass.cpp, test/dd/test_dd_functionality.cpp, test/ir/test_io.cpp, test/ir/test_qasm3_parser.cpp
This pull request introduces the following enhancements and fixes for the OpenQASM parser and type checker:
- Adds support for indexed identifiers and index operators in the OpenQASM parser and type checker.
- Fixes incorrect OpenQASM 3 dump for single-bit classic-controlled operations.
- Canonicalizes single-bit classic-controlled operations for consistency.
- Implements dedicated sanity checks on single-bit classic-controlled operations.
- Addresses several Clang-Tidy suggestions to improve code quality.
These changes aim to enhance functionality, ensure correctness, and improve maintainability of the OpenQASM implementation.
=> 🚸 Add support for indexed identifiers and improve OpenQASM handling

cmake/ExternalDependencies.cmake
This pull request updates the following dependencies to their latest stable versions:
- `googletest`: from `1.14.0` to `1.16.0`
- `Boost Multiprecision`: from `1_84_0` to `1_86_0`
These updates bring in the latest fixes, performance improvements, and compatibility enhancements. No new dependencies are introduced.
=> ⬆️ Update googletest and Boost Multiprecision dependencies

cmake/StandardProjectSettings.cmake
Basically the PR title. From past experience, IPO can make debugging quite hard.
This PR ensures that, at least in non-release builds, IPO is not enabled by default.
As such, no manual workarounds should be necessary anymore for debugging.
This change transitively propagates to all dependants of MQT Core once they update to the latest version.
@ystade tagging for awareness
=> 🔧 Only enable IPO per default for Release builds outside of deployment

.github/renovate.json5, noxfile.py, pyproject.toml, uv.lock
This pull request introduces a series of improvements including enabling automerge for minor stable dependency updates and lockfile update pull requests. It also updates the lockfile, upgrades the `sphinx` and `scikit-build-core` dependencies, and improves compliance by utilizing PEP 639 license expressions. Additionally, it addresses issues with the docs nox session command sequence and introduces verbose logging for install commands.
Fixes #None
=> ⬆️ scikit-build-core 0.11, PEP 639 license expressions, sphinx fixes, more automerge

src/mqt/core/plugins/qiskit.py, test/python/plugins/test_qiskit.py
This pull request adds support for handling empty quantum and classical registers during the translation process from Qiskit to MQT. This update ensures proper translation and eliminates any potential errors caused by empty registers.
This has come up while working on https://github.com/cda-tum/mqt-ddsim/pull/336
=> 🔧 Handle empty quantum and classical registers in qiskit to MQT translation

src/mqt/core/ir/__init__.pyi, src/mqt/core/plugins/qiskit.py, src/python/ir/register_permutation.cpp, test/python/plugins/test_qiskit.py
This pull request includes several improvements and fixes to the Qiskit layout and permutation handling logic. Key changes:
- Fixed and simplified the Qiskit layout handling mechanism.
- Fixed type stubs for the permutation constructor to ensure type safety.
- Added a new `clear` method to the permutation class for easier reset functionality.
- Corrected issues with the permutation setter.
- Enhanced the permutation representation for cleaner and more intuitive display.
These changes aim to improve functionality, maintainability, and user experience in working with layouts and permutations.
=> 🐛 Fix and enhance Qiskit layout and permutation handling

include/mqt-core/ir/Permutation.hpp, src/ir/QuantumComputation.cpp, src/mqt/core/ir/__init__.pyi, src/mqt/core/plugins/qiskit.py, src/python/ir/register_permutation.cpp, src/qasm3/Parser.cpp, src/qasm3/passes/TypeCheckPass.cpp
This PR refactors the `qc::Permutation` class to not subclass from `std::map`. This has caused more harm than good, especially in the Python bindings, where pybind automatically binds some of the `std::map` members and then won't accept them being called on a `Permutation` object.
This creates quite a bit of boilerplate code for exposing the `map` interface in the permutation class, but has no other major influence (except that the Python bindings now work properly).
Additionally, this fixes an error related to the layout import from Qiskit related to https://github.com/Qiskit/qiskit/issues/12749. It turns out that calling the public API of the `TranspileLayout` may throw errors if the `final_layout` is `None`.
Last, but not least, this PR adds a warnings ignore filter for a nonsense GCC …
=> ♻️🐛 Refactor  `qc::Permutation` and fix corner case in Qiskit layout import 

include/mqt-core/ir/operations/CompoundOperation.hpp, pyproject.toml, src/mqt/core/ir/__init__.pyi, src/mqt/core/ir/operations.pyi, src/mqt/core/plugins/qiskit/__init__.py, src/mqt/core/plugins/qiskit/mqt_to_qiskit.py, src/mqt/core/plugins/qiskit/qiskit_to_mqt.py, src/python/ir/operations/register_compound_operation.cpp, src/python/ir/register_permutation.cpp, src/python/ir/register_quantum_computation.cpp, src/python/ir/register_registers.cpp, test/python/plugins/test_qiskit.py
This pull request introduces several changes to enhance Python interoperability and integration with Qiskit. Key updates include:
- Adding a method to natively export `QuantumComputations` objects to Qiskit `QuantumCircuit`.
- Exposing registers from `QuantumComputation` in the Python interface.
- Addressing issues with calling `name` and `end` on Python registers.
- Fixing the implementation of `__iter__` and providing `items` for `Permutation`.
- Enhancing `CompoundOperation` to implement the `MutableSequence[Operation]` interface.
These changes provide better usability and extend functionality when using the library in Python environments.
Fixes #35
=> ✨ Add Python interface improvements and Qiskit export support

include/mqt-core/ir/Permutation.hpp
Fixes an oversight when switching from directly inheriting from `std::map` for the `qc::Permutation` class. One of the downstream packages (https://github.com/cda-tum/mqt-syrec) relied on the `insert_or_assign` method being available.
=> 🩹 Add `insert_or_assign` method to `Permutation` class

include/mqt-core/dd/CachedEdge.hpp, include/mqt-core/dd/Edge.hpp, include/mqt-core/dd/LinkedListBase.hpp, include/mqt-core/dd/MemoryManager.hpp, include/mqt-core/dd/Node.hpp, include/mqt-core/dd/Package.hpp, include/mqt-core/dd/RealNumber.hpp, include/mqt-core/dd/RealNumberUniqueTable.hpp, include/mqt-core/dd/UniqueTable.hpp, include/mqt-core/dd/statistics/MemoryManagerStatistics.hpp, src/dd/CachedEdge.cpp, src/dd/Edge.cpp, src/dd/MemoryManager.cpp, src/dd/RealNumber.cpp, src/dd/RealNumberUniqueTable.cpp, src/dd/UniqueTable.cpp, src/dd/statistics/MemoryManagerStatistics.cpp, test/dd/test_complex.cpp, test/dd/test_package.cpp
Main Changes:
- Remove template from MemoryManagerStatistics
-> only used to get size of an object, replaced by a member field that specifies the size of the object that is being tracked
- Separate next pointer for linked lists in base class
-> allows to use memory manager with static_cast to base class without templates
- Separate common members in Node classes into base class
-> allows to move some methods of UniqueTable into source files. Some methods are still explicitly templated if exact node data (e.g. equality of nodes) is required
This also decreases code size :)
(will solve the linter errors on sunday if you want to go down the route of more runtime config and less templating)
=> ♻️ Remove template parameter from MemoryManager and adjacent classes

include/mqt-core/ir/operations/OpType.inc, include/mqt-core/ir/operations/StandardOperation.hpp, include/mqt-core/qasm3/StdGates.hpp, src/ir/QuantumComputation.cpp, src/ir/operations/OpType.cpp, src/ir/operations/StandardOperation.cpp, src/mqt/core/ir/operations.pyi, src/python/ir/operations/register_optype.cpp, test/ir/test_qasm3_parser.cpp, test/ir/test_qfr_functionality.cpp
This PR removes the `Teleportation` gate from mqt-core in preparation for the v3 launch.
It was only ever used in one routing pass in MQT QMAP that is being phased out and was hardly documented.
Might as well remove it here. Removed code is debugged code 🤷🏼
=> 🔥 Remove `Teleportation` gate

.github/workflows/ci_mlir.yml, mlir/CMakeLists.txt, mlir/lib/Dialect/MQTOpt/Transforms/MQTCoreRoundTrip.cpp
This PR updates the `CMakeLists.txt` file of the `mlir` subdirectory to now check whether the found MLIR package uses version `20.0` or newer. Otherwise, compilation stops.
Due to this change in compatibility, `llvm-19` was removed from the CI build matrix and transformation passes now use `applyPatternsGreedily` instead of `applyPatternsAndFoldGreedily`.
I suggest we wait until #892 is merged so that we can also fix the deprecated calls in there.
=> :building_construction: Enforce LLVM-20 when building MLIR subdirectory

src/zx/CMakeLists.txt
This PR restores the installation of the Boost multiprecision headers to ensure that they are installed together with the mqt-core package. This fixes a regression introduced when adopting file sets in mqt-core.
=> 🐛 restore installation of Boost multiprecision headers

.github/workflows/ci_mlir.yml, CHANGELOG.md, mlir/CMakeLists.txt, mlir/include/mlir/Dialect/Common/Compat.h, mlir/lib/Dialect/MQTDyn/Transforms/ConstantFolding.cpp, mlir/lib/Dialect/MQTOpt/Transforms/CancelConsecutiveInverses.cpp, mlir/lib/Dialect/MQTOpt/Transforms/MQTCoreRoundTrip.cpp, mlir/lib/Dialect/MQTOpt/Transforms/QuantumSinkPass.cpp
Reincarnate MLIR / LLVM 19.0 support.
Necessary for Catalyst-related efforts (like #880).
=> ⏪️ [MLIR] Bring back MLIR / LLVM 19.0 support 

.pre-commit-config.yaml, CHANGELOG.md, docs/index.md, docs/mlir.md, mlir/include/mlir/Dialect/Common/IR/CommonTraits.h, mlir/include/mlir/Dialect/MQTDyn/IR/MQTDynInterfaces.td, mlir/include/mlir/Dialect/MQTOpt/IR/MQTOptInterfaces.td, mlir/include/mlir/Dialect/MQTOpt/IR/MQTOptOps.td, mlir/lib/Dialect/MQTOpt/Transforms/CancelConsecutiveInversesPattern.cpp, mlir/lib/Dialect/MQTOpt/Transforms/FromQuantumComputationPattern.cpp, mlir/lib/Dialect/MQTOpt/Transforms/QuantumSinkPushPattern.cpp, mlir/lib/Dialect/MQTOpt/Transforms/QuantumSinkShiftPattern.cpp, mlir/lib/Dialect/MQTOpt/Transforms/ToQuantumComputationPattern.cpp, mlir/test/Dialect/MQTOpt/IR/bell_state_value_dialect.mlir, mlir/test/Dialect/MQTOpt/Transforms/consecutive-inverses.mlir, mlir/test/Dialect/MQTOpt/Transforms/to-quantum-computation.mlir
Until now, operations of the MQTopt dialect had different variadic operands for target qubits and positively and negatively control qubits but only one result type. We decided that it is desirable to have the same distinction also in the results. Hence, this PR mirrors the separation for the qubit operands also for the qubit results.
Additionally, this PR creates an initial subpage in the documentation for our MLIR efforts. In particular, it kickstarts a FAQ that can be extended on demand. This page, including the FAQ, should serve as a common knowledge base about MLIR in MQT.
=> ♻️ [MLIR] Unify Operands and Results and add Docs Page for MLIR

.github/workflows/ci_mlir.yml
#936 broke the MLIR workflow. This went unnoticed because the MLIR workflow would not trigger on workflow-only changes.
This PR fixes the oversight and enables the CI to run on workflow-only changes, which should be demonstrated by this PR.
=> 🩹 Fix MLIR workflow

.github/workflows/ci_mlir.yml
This PR adds MLIR CI tests for windows runners.
This is achieved by building MLIR from source so the first execution should take a bit longer.
Afterwards, the cache will be used to store the built versions of MLIR.
This PR contributes to #925
**Note:** To install a specific version, the runner clones the tag `llvmorg-{version}.1.0`. It seems that the first release of a new major `llvm-project` version is typically called `{version}.1.0` so this should keep working, but there is no guarantee.
=> :construction_worker: add windows CI for MLIR

CMakeLists.txt, cmake/AddMQTCoreLibrary.cmake, src/algorithms/CMakeLists.txt, src/circuit_optimizer/CMakeLists.txt, src/datastructures/CMakeLists.txt, src/dd/CMakeLists.txt, src/ir/CMakeLists.txt, src/na/CMakeLists.txt, src/qasm3/CMakeLists.txt, src/zx/CMakeLists.txt
Pulled out from #881.
Adds a convenience macro for adding MQT Core libraries and corresponding aliases.
=> 🚸 add convenience macro for adding MQT Core libraries

CMakeLists.txt, cmake/AddMQTCoreLibrary.cmake, pyproject.toml, src/algorithms/CMakeLists.txt, src/circuit_optimizer/CMakeLists.txt, src/datastructures/CMakeLists.txt, src/dd/CMakeLists.txt, src/ir/CMakeLists.txt, src/na/CMakeLists.txt, src/qasm3/CMakeLists.txt, src/zx/CMakeLists.txt
Also pulled out from #881.
Builds on #961 and adds a dedicated option for only building the MQT Core libraries as shared libraries without forcing this on every other library.
=> 🚸 Add dedicated option for only building MQT Core as shared libraries

CMakeLists.txt, cmake/SetupMLIR.cmake, mlir/CMakeLists.txt
Also pulled out of #881.
Adds a top-level MLIR setup call, which ensures that other top-level directories (e.g., the future `plugins` directory) also have access to MLIR and the respective variables.
=> 🚸 add dedicated MLIR setup file

CMakeLists.txt, bindings/dd/CMakeLists.txt, bindings/dd/register_dd.cpp, bindings/ir/CMakeLists.txt, bindings/ir/register_ir.cpp, cmake/AddMQTPythonBinding.cmake
This PR makes the function for adding Python bindings reusable across MQT repositories. The function has been added in
=> 🚸 Make CMake function for adding Python bindings reusable

.pre-commit-config.yaml
This PR makes it so that `pre-commit` fails immediately if it detects a merge conflict.
The action added in https://github.com/munich-quantum-toolkit/templates/pull/1 may create PRs with merge conflicts. These merge conflicts should be resolved manually by a developer. The changes in this PR ensure that merge markers are not formatted by subsequent hooks.
=> 🎨 Stop pre-commit if there are merge conflicts

python/mqt/core/plugins/__init__.py
This PR removes the reexport of the `qiskit` plugin in the `mqt.core.plugins` module.
It was noticed during working on #881 that this would lead to Python trying to import the plugin even if that was not explicitly requested, e.g. as part of an import `from mqt.core.plugins.catalyst import ...`.
=> 🔥 do not eagerly import Qiskit plugin

.github/workflows/ci.yml, cmake/ExternalDependencies.cmake, pyproject.toml, uv.lock
This PR updates the `pybind11` lower bound to v3.0.0.
At the moment, we do not make use of any of the latest major release's features.
However, this is clearly the plan. Especially the new native enum support as well as the better compatibility between extensions compiled with different compiler versions.
=> ⬆️ raise `pybind11` lower bound to `v3.0.0`

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/upstream.yml
This PR builds on the workflow improvements from munich-quantum-toolkit/workflows#146 and streamlines the CI/CD configurations.
The most important changes:
- Debug builds on Ubuntu are enabled by default again to have at least one workflow with assertions enabled.
- Regular and extensive tests are now exclusive instead of complementary.
- The extensive testing matrix for C++ is much broader.
=> ⬆️  Update CI/CD testing configuration

mlir/lib/Conversion/MQTDynToMQTOpt/MQTDynToMQTOpt.cpp
This PR adds the class `StatefulOpConversionPattern` which takes a pointer to a `LoweringState` object as a parameter and stores it as member. All `ConvertMQTDyn{OP}` classes inherit from this new class. 
This reduces boilerplate code and removes the slightly awkward use of pointers.
=> ♻️ Add `StatefulOpConversionPattern` class

CHANGELOG.md, mlir/include/mlir/Dialect/MQTOpt/IR/MQTOptOps.td, mlir/lib/Conversion/MQTOptToMQTRef/MQTOptToMQTRef.cpp, mlir/lib/Conversion/MQTRefToMQTOpt/MQTRefToMQTOpt.cpp, mlir/test/Conversion/mqtopt-to-mqtref.mlir, mlir/test/Conversion/mqtref-to-mqtopt.mlir, mlir/test/Dialect/MQTOpt/IR/dialect_features.mlir, mlir/test/Dialect/MQTRef/IR/dialect_features.mlir
Resolves #1114 by adding a `Qubit` operation to the `mqtopt` dialect and implementing the respective conversion functions. 
- As stated in the description of the `InsertOp` operation: It is possible to insert a static qubit into a quantum register. 
- A static qubit automatically "inserts" itself at the end of the scope where it was defined.
=> ✨ Add `Qubit` operation to `mqtopt` dialect

CHANGELOG.md, mlir/include/mlir/Dialect/MQTOpt/Transforms/Passes.h, mlir/include/mlir/Dialect/MQTOpt/Transforms/Passes.td, mlir/lib/Dialect/MQTOpt/Transforms/ElidePermutations.cpp, mlir/lib/Dialect/MQTOpt/Transforms/ElidePermutationsPattern.cpp, mlir/test/Dialect/MQTOpt/Transforms/elide-permutations.mlir
This PR adds a MLIR pass to eliminate all SWAP gates. This can be used on unmapped circuits to reduce the amount of needed swaps or in combination with another optimization called swap reconstruction to remove repeated CNOTs on two qubits.
Related to https://github.com/munich-quantum-toolkit/core/issues/1122
=> :sparkles: Implement elide permutations pass in MLIR

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/reusable-mlir-tests.yml, CHANGELOG.md, UPGRADING.md, cmake/StandardProjectSettings.cmake, pyproject.toml
This PR drops running our tests and deployment workflows on `macos-13` runners.
Hence, this marks the end of us shipping macOS x86 wheels with MQT Core.
While I do not expect any immediate problems and incompatibilities, this means that people still on those systems will either have to stick with an old version of MQT Core or will have to build the new version from source.
I'll let this sit in draft for a while until it becomes relevant.
If nothing bigger comes up, this will be part of the next minor release.
=> 🍎🔥 Stop testing on `x86` macOS and shipping wheels for Intel-based Macs

.readthedocs.yaml
In #1091 the RTD build does not show the updates of the MLIR docs because the RTD build is skipped due to a misconfiguration of RTD. This PR fixes the configuration and also triggers an RTD build on changes in the MLIR header files.
=> 🔧 Trigger RTD Build also on Changes in MLIR Directory
